status-im/StatusQ

- src/StatusQ/Core/StatusBaseText.qml
- src/StatusQ/Core/qmldir
Abstract text component that defaults to Status' `Inter` font.
Also known as `StyledText` in Status Desktop.
This will close #20 as it doesn't make sense to implement multiple
components for a single text type. Size and weight of text can be configured
on a per usage basis.
Closes #20
> feat(Core): introduce StatusBaseText component

- sandbox/Others.qml
- src/StatusQ/Components/StatusRoundedImage.qml
- src/StatusQ/Components/qmldir
A component that renders an image as a circle, given some URL.
Usage:
```
StatusRoundedImage {
image.source: "..." // some url
}
```
Closes #32
> feat(Components): introduce StatusRoundedImage

- sandbox/Buttons.qml
- sandbox/main.qml
- sandbox/qml.qrc
- sandbox/sandbox.pro
- src/StatusQ/Controls/StatusBaseButton.qml
- src/StatusQ/Controls/StatusButton.qml
- src/StatusQ/Controls/StatusFlatButton.qml
- src/StatusQ/Controls/StatusFlatRoundButton.qml
- src/StatusQ/Controls/StatusRoundButton.qml
- src/StatusQ/Controls/qmldir
> feat: Add buttons components

- sandbox/main.qml
- sandbox/sandbox.pro
- sandbox/sandboxapp.cpp
- sandbox/sandboxapp.h
- sandbox/statuswindow.h
- sandbox/statuswindow_mac.mm
> fix: fix crash on removing title bar

- src/StatusQ/Controls/StatusRadioButton.qml
> fix(StatusRadioButton): ensure control label as correct color

- src/StatusQ/Components/StatusBadge.qml
- src/StatusQ/Core/Theme/StatusDarkTheme.qml
- src/StatusQ/Core/Theme/StatusLightTheme.qml
- src/StatusQ/Core/Theme/ThemePalette.qml
> fix(Components): add proper foreground color for StatusBadge

- sandbox/ListItems.qml
- src/StatusQ/Components/StatusDescriptionListItem.qml
- src/StatusQ/Components/qmldir
Usage:
```qml
StatusDescriptionListItem {
title: "Title"
subTitle: "Subtitle"
}
StatusDescriptionListItem {
title: "Title"
subTitle: "Subtitle"
tooltip.text: "Tooltip"
icon.name: "info"
iconButton.onClicked: tooltip.visible = !tooltip.visible
}
```
Closes: #73
> feat(Components): introduce `StatusDescriptionListItem`

- src/StatusQ/Components/StatusChatListItem.qml
- src/StatusQ/Controls/StatusChatInfoButton.qml
- src/StatusQ/Controls/StatusIconTabButton.qml
> refactor: make use of `StatusRoundImage`'s built-in loading indicator

- sandbox/DemoApp.qml
- sandbox/main.qml
This reference app serves as a dogfooding ground for StatusQ components.
> feat(sandbox): introduce first version of reference app

- README.md
- sandbox/DemoApp.qml
- sandbox/StatusPopupMenuPage.qml
- sandbox/main.qml
- src/StatusQ/Core/Theme/StatusDarkTheme.qml
- src/StatusQ/Core/Theme/StatusLightTheme.qml
- src/StatusQ/Core/Theme/ThemePalette.qml
- src/StatusQ/Popups/StatusMenuItem.qml
- src/StatusQ/Popups/StatusMenuSeparator.qml
- src/StatusQ/Popups/StatusPopupMenu.qml
- src/StatusQ/Popups/qmldir
Usage:
```qml
import StatusQ.Popups 0.1
Button {
onClicked: simpleMenu.popup()
}
StatusPopupMenu {
id: simpleMenu
text: "One"
}
text: "Two"
}
text: "Three"
}
}
```
Closes #96 #74
> feat(StatusQ.Popups): introduce StatusPopupMenu component

- src/StatusQ/Components/StatusChatToolBar.qml
Also expose action buttons for more custom control.
> fix(StatusChatToolBar): ensure context menu as proper position

- src/StatusQ/Components/StatusChatListCategory.qml
- src/StatusQ/Components/StatusChatToolBar.qml
- src/StatusQ/Components/StatusListItem.qml
Also triggers the context menu in `StatusChatListCategory`.
Fixes #131
> feat(StatusChatListItem): accept right clicks

- sandbox/DemoApp.qml
- src/StatusQ/Popups/StatusPopupMenu.qml
> feat(StatusPopupMenu): make menu items invisible when disabled

- src/StatusQ/Components/StatusListItem.qml
- src/StatusQ/Controls/StatusRoundButton.qml
This also exposes `statusListItemSubTitle` for more control over
it's appearance, if needed.
> fix(StatusListItem): various fixes w.r.t. sensor, icon size etc

- README.md
- sandbox/scripts/build
> chore: introduce build script for sandbox app

- sandbox/DemoApp.qml
- sandbox/main.qml
- sandbox/qml.qrc
- src/StatusQ/Components/StatusListSectionHeadline.qml
- src/StatusQ/Components/StatusNavigationPanelHeadline.qml
- src/StatusQ/Components/qmldir
- statusq.qrc
Usage:
```qml
StatusListSectionHeadline {
text: "Settings"
}
```
Closes #164
> feat(Components): introduce `StatusListSectionHeadline`

- sandbox/DemoApp.qml
- sandbox/main.qml
- sandbox/qml.qrc
- src/StatusQ/Components/StatusListSectionHeadline.qml
- src/StatusQ/Components/StatusNavigationPanelHeadline.qml
- src/StatusQ/Components/qmldir
- statusq.qrc
> feat(sandbox): introduce first part of profile view for reference app

- src/StatusQ/Components/StatusChatList.qml
- src/StatusQ/Components/StatusChatListItem.qml
> fix(StatusChatList): ensure component provide default `width`

- src/StatusQ/Popups/statusModal/StatusModalHeader.qml
> fix(StatusModalHeader): ensure header has enough height for children

- src/StatusQ/Components/StatusChatListItem.qml
- src/StatusQ/Controls/StatusChatInfoButton.qml
> refactor: make chat component enum variants match protocol values

- sandbox/DemoApp.qml
- sandbox/ListItems.qml
- src/StatusQ/Components/StatusContactRequestsIndicatorListItem.qml
- src/StatusQ/Components/qmldir
- statusq.qrc
Usage:
```qml
StatusContactRequestsIndicatorListItem {
title: "Contact requests"
requestsCount: 3
sensor.onClicked: ...
}
```
Closes #175
> feat(Components): introduce `StatusContactRequestsIndicatorListItem`

- sandbox/DemoApp.qml
- src/StatusQ/Components/StatusChatList.qml
- src/StatusQ/Components/StatusChatListCategory.qml
> refactor(StatusPopupMenu): expose category and chat id via open handler

- sandbox/DemoApp.qml
- src/StatusQ/Components/StatusChatListItem.qml
> fix(StatusChatListItem): ensure public chat names are prefixed with '#'

- sandbox/DemoApp.qml
- src/StatusQ/Components/StatusChatListItem.qml
> fix(StatusChatListItem): ensure chat name elides when it's too long

- src/StatusQ/Components/StatusLoadingIndicator.qml
> bug(StatusLoadingIndicator): Change Animator to Animation

- src/StatusQ/Popups/StatusMenuSeparator.qml
> fix(StatusMenuSeparator): ensure height is 0 when invisible or disabled

- src/StatusQ/Components/StatusChatListAndCategories.qml
> fix(StatusChatListAndCategories): ensure chat list receives popup menu

- src/StatusQ/Components/StatusChatListAndCategories.qml
> fix(StatusChatListAndCategories): make chat list visibily flag work

- src/StatusQ/Components/StatusChatListCategory.qml
> fix(StatusChatListCategory): only try open popup when supplied

- src/StatusQ/Controls/StatusChatInfoButton.qml
> fix(StatusChatInfoButton): disable hover effects when sensor is disabled

- src/StatusQ/Controls/StatusChatInfoButton.qml
> fix(StatusChatInfoButton): prefix chat name with "#" if needed

- src/StatusQ/Controls/StatusChatInfoButton.qml
> fix(StatusChatInfoButton): make component identicon aware

- sandbox/Buttons.qml
- sandbox/main.qml
- sandbox/sandbox.pro
- src/StatusQ/Controls/StatusPickerButton.qml
- src/StatusQ/Controls/qmldir
Adding picker button
* As an example it opens Qt's ColorDialog, as soon as
a color is selected there, the button is colored
with that. Final color picker to be implemented in
a seperate task.
Also minor improvements in main.qml and sandbox.pro
fixes #202
> [#202] Added Picker button

- src/StatusQ/Controls/StatusBaseInput.qml
> fix(StatusBaseInput): Fix focus area

- sandbox/ListItems.qml
- src/StatusQ/Components/StatusListItem.qml
> feat(StatusListItem): add identicon support

- sandbox/Popups.qml
- src/StatusQ/Core/StatusModalHeaderSettings.qml
- src/StatusQ/Popups/StatusModal.qml
- src/StatusQ/Popups/statusModal/StatusImageWithTitle.qml
- src/StatusQ/Popups/statusModal/StatusModalHeader.qml
Usage:
```qml
StatusModal {
header.image.isIdenticon: ...
// or
header.icon.isLetterIdenticon: ...
header.icon.background.color: ...
}
```
Closes #269
> feat(StatusModal): introduce support for identicons and letter identicons

- sandbox/ListItems.qml
- src/StatusQ/Components/StatusListItem.qml
Usage:
```qml
StatusListItem {
title: ...
subTitle: ...
tertiaryTitle: ...
}
```
Closes #275
> feat(StatusListItem): support tertiaryTitle

- src/StatusQ/Controls/StatusChatInfoButton.qml
> fix(StatusChatInfoButton): ensure pin icon button is always rendered

- sandbox/DemoApp.qml
- src/StatusQ/Layout/StatusAppThreePanelLayout.qml
- src/StatusQ/Layout/qmldir
Added new component to support a 3 column view      
Closes #272
> feat(StatusQ.Layout): introducing StatusAppThreePanelLayout

- src/StatusQ/Layout/StatusAppThreePanelLayout.qml
Brought back opacity condition deleted by mistake
> feat(StatusQ.Layout): StatusAppThreePanelLayout

- sandbox/DemoApp.qml
- src/StatusQ/Layout/StatusAppThreePanelLayout.qml
Also added handle in DemoApp as well as hiding text when in minimum
width for right and left panels
> fix(StatusAppThreePanelLayout): limit right panel width to 300px

- src/StatusQ/Components/StatusListItem.qml
This was needed to "lock" the requirement for the community type
> feat(StatusListItem): add enabled prop to StatusLIneItem

- src/StatusQ/Components/StatusChatList.qml
> fix(StatusChatListItem): don't signal item selection if already selected

- src/StatusQ/Layout/StatusAppNavBar.qml
Adds a property that lets you add an additional button that's fixed at the bottom of the navbar
> fix(StatusAppNavBar): add profile button

- sandbox/DemoApp.qml
- src/StatusQ/Popups/StatusSearchPopup.qml
@alexandraB99 here are some fixes that you can review. We'll squash them into your PR once you're good with these.
There are a few more which I'll add on top of this
> Issue 264 fixes

- src/StatusQ/Popups/StatusPopupMenu.qml
> fix(StatusPopupMenu): ensure icon or image settings exist

- sandbox/DemoApp.qml
- sandbox/ListItems.qml
- sandbox/Models.qml
- sandbox/StatusPopupMenuPage.qml
- src/StatusQ/Components/StatusLetterIdenticon.qml
- src/StatusQ/Components/StatusListItem.qml
- src/StatusQ/Components/StatusListItemBadge.qml
- src/StatusQ/Components/qmldir
- src/StatusQ/Controls/StatusBaseInput.qml
- src/StatusQ/Controls/StatusInput.qml
- src/StatusQ/Popups/StatusModal.qml
- src/StatusQ/Popups/StatusPopupMenu.qml
- src/StatusQ/Popups/StatusSearchLocationMenu.qml
- src/StatusQ/Popups/StatusSearchPopup.qml
- src/StatusQ/Popups/StatusSearchPopupMenuItem.qml
- src/StatusQ/Popups/qmldir
- src/StatusQ/Popups/statusModal/StatusModalFooter.qml
- src/StatusQ/Popups/statusModal/StatusModalHeader.qml
- statusq.qrc
> feat(StatusQ.Popups) Adding SearchPopup component

- src/assets/img/icons/pause-filled.svg
- src/assets/img/icons/play-filled.svg
> feat(StatusIcon): add `play-filled` and `pause-filled` icons

- sandbox/DemoApp.qml
- sandbox/Models.qml
- src/StatusQ/Components/StatusChatListCategoryItem.qml
- src/StatusQ/Components/StatusListItem.qml
- src/StatusQ/Components/StatusNavigationListItem.qml
- src/StatusQ/Popups/StatusSearchLocationMenu.qml
- src/StatusQ/Popups/StatusSearchPopup.qml
- src/StatusQ/Popups/StatusSearchPopupMenuItem.qml
Changes needed for the desktop part of issue-2934 are added.
> Status search popup component updates

- src/StatusQ/Controls/StatusBaseInput.qml
> fix(StatusBaseInput): expose cursorPosition

- src/StatusQ/Controls/StatusBaseInput.qml
- src/StatusQ/Controls/StatusInput.qml
> fix(StatusInput): ensure validation is performed on initialization

- src/StatusQ/Components/StatusLetterIdenticon.qml
Aliased the text compoenent so that its color, text value can be set from outside
> feat(StatusLetterIdenticon): Expose the text component

- src/StatusQ/Components/StatusListItem.qml
> fix(StatusListItem): Add propogateCompostedEvents to title mouse area

- sandbox/Models.qml
- src/StatusQ/Popups/StatusSearchPopup.qml
This change follows model update in the `status-desktop` repo.
Relates to the issue #3259.
> fix(@desktop/chat): no identicon/profile picture shown and wrong time stamp format in search results

- src/StatusQ/Components/StatusChatToolBar.qml
> fix(StatusChatToolBar): Fix mouse event catching after menu closing

- sandbox/ListItems.qml
- sandbox/Popups.qml
- src/StatusQ/Components/StatusDescriptionListItem.qml
- src/StatusQ/Core/StatusModalHeaderSettings.qml
- src/StatusQ/Popups/StatusModal.qml
- src/StatusQ/Popups/statusModal/StatusImageWithTitle.qml
- src/StatusQ/Popups/statusModal/StatusModalHeader.qml
This adds a new `value` property to the component to set label for a
selected value and also rendering a chevron as an indicator that the list
item becomes clickable.
> feat(StatusDescriptionListItem): introduce support for `value`

- src/StatusQ/Components/StatusChatListAndCategories.qml
> feat(StatusChatListAndCategories): Add tooltip settings for categories buttons

- src/StatusQ/Controls/StatusBaseInput.qml
> fix(StatusBaseInput): fix one line scroll

- src/StatusQ/Controls/StatusBaseInput.qml
- src/StatusQ/Controls/StatusInput.qml
> fix(StatusInput): Forward keys events to root

- sandbox/StatusInputPage.qml
- src/StatusQ/Controls/StatusBaseInput.qml
- src/StatusQ/Controls/StatusInput.qml
Due to design updates in AddAccount modal, updates are needed in StatusBaseInput and StatusInput
* Added the possibility of having the icon on the right
side
* Added secondaryLabel for title
* Added examples in StatusInputPage
Closes #383
>  feat(StatusInput): Introduced secondaryLabel property

- sandbox/Popups.qml
- src/StatusQ/Popups/statusModal/StatusImageWithTitle.qml
> fix(StatusModal): don't reserve header subtitle space

- sandbox/sandbox.pro
> feat(Spellchecking): Add hunspell dependency

- sandbox/sandbox.pro
- sandbox/sandboxapp.cpp
- sandbox/spellchecker.cpp
- sandbox/spellchecker.h
Closes: #399
Should be merge after https://github.com/status-im/StatusQ/pull/404
> feat(Spellchecker): Add Spellchecker class

- src/StatusQ/Controls/StatusInput.qml
This can be used to reset text, error message and validity state of inputs
> feat(StatusInput): introduce `reset` API

- sandbox/Popups.qml
- src/StatusQ/Popups/StatusSpellcheckingMenuItems.qml
- src/StatusQ/Popups/qmldir
- statusq.qrc
> feat(StatusSpellcheckingMenuItems): Add spellchecking menu

- src/StatusQ/Popups/StatusSpellcheckingMenuItems.qml
Sometimes menu items is lost order.
> fix(StatusSpellcheckingMenuItems): Exact  menu items order

- sandbox/Controls.qml
- src/StatusQ/Controls/StatusChatInfoButton.qml
- src/StatusQ/Controls/StatusSelectableText.qml
- src/StatusQ/Controls/qmldir
- statusq.qrc
feature(StatusSelectableText): Added a selectable text component
Features:
1. Select text and copy it
2. Custom highlight on selection
3. Highlight on links
4. Support for multiline text
> feature(StatusSelectableText): Added a selectable text component

- src/StatusQ/Core/StatusModalHeaderSettings.qml
- src/StatusQ/Popups/StatusModal.qml
- src/StatusQ/Popups/statusModal/StatusImageWithTitle.qml
- src/StatusQ/Popups/statusModal/StatusModalHeader.qml
- statusq.qrc
Part of https://github.com/status-im/status-desktop/issues/3734
> feat(StatusModal): Add edit avatar button

- sandbox/StatusColorSelectorPage.qml
- sandbox/main.qml
- src/StatusQ/Controls/StatusColorSelector.qml
- src/StatusQ/Controls/qmldir
- statusq.qrc
This is a select component to pick from various supplied colors.
Usage:
```qml
import StatusQ.Controls 0.1
StatusColorSelector {
model: ["red", "blue", "green"]
}
```
Closes #444
> feat(StatusQ.Controls): introduce StatusColorSelector component

- src/StatusQ/Controls/StatusChatInfoButton.qml
added object name for `Muted Icon` in `StatusChatInfoButton.qml`
> chore(StatusChatInfoButton): add object name for testing purposes

- src/StatusQ/Controls/StatusChatInfoButton.qml
chore(StatusChatInfoButton): add object name for pin counter for testing purposes
> chore(StatusChatInfoButton): add object name for pin counter for testing purposes

- sandbox/StatusAssetSelectorPage.qml
- src/StatusQ/Controls/StatusAssetSelector.qml
Also added error handling in case in case that crypto symbol image is not available
Added a way to display the balance in currently selected currency on the widget
To do this the consumer of this widget needs to implement "getCurrencyBalanceString" based on the currently selected currency
fixes #4079
> fix(StatusAssetSelector): Fixed error of crypto balance not updated correctly

- src/StatusQ/Layout/StatusAppNavBar.qml
fix(StatusAppNavBar): Fixed position of profile button on the NavBar
fixes #3521
> fix(StatusAppNavBar): Fixed position of profile button on the NavBar

- sandbox/DemoApp.qml
- sandbox/Layout.qml
- sandbox/Models.qml
- sandbox/main.qml
This feature is deprecated and shall be removed
Relates to #4177
> refactor(sandbox): remove obsolete timeline demo code

- sandbox/Popups.qml
- src/StatusQ/Components/StatusListItem.qml
- src/StatusQ/Popups/statusModal/StatusImageWithTitle.qml
feat(StatusListItem): Expose the Aside text so that it can be modified from the outside
> feat(StatusListItem): Expose the Aside text so that it can be modified from the outside

- src/StatusQ/Controls/StatusBaseInput.qml
fix(StatusBaseInput): Corrects alignment of the placeholder text in the StatusBaseInput.
> fix(StatusBaseInput): Corrects allignment of the placeholder text in the StatusBaseInput.

- sandbox/sandbox.pro
- sandbox/sandboxapp.cpp
This fix add minor changes for a correct build and run sandbox in Windows.
> fix(build): Windows build

- sandbox/sandbox.pro
moved DESTDIR in sandbox.pro above copydata command as it was breaking the build process on MacOS
> fix(build): broken MacOS build

- sandbox/DemoApp.qml
- sandbox/Models.qml
- sandbox/controls/Layout.qml
- sandbox/controls/ListItems.qml
- sandbox/main.qml
- src/StatusQ/Components/StatusChatList.qml
- src/StatusQ/Components/StatusChatListAndCategories.qml
- src/StatusQ/Components/StatusChatListCategory.qml
- src/StatusQ/Components/StatusChatListItem.qml
- src/StatusQ/Components/StatusChatToolBar.qml
- src/StatusQ/Core/StatusAppNavBarFilterModel.qml
- src/StatusQ/Core/qmldir
- src/StatusQ/Layout/StatusAppNavBar.qml
- statusq.qrc
This should not be merged until we are ready to merge this: 
- https://github.com/status-im/status-desktop/pull/3951
> Base branch for refactoring bc

- sandbox/main.qml
- sandbox/pages/StatusWizardStepperPage.qml
- src/StatusQ/Components/StatusWizardStepper.qml
- src/StatusQ/Components/qmldir
- src/StatusQ/Controls/StatusProgressBar.qml
- statusq.qrc
Added StatusWizardStepper component
Also added corresponding page in API documentation
Closes #522
https://user-images.githubusercontent.com/31625338/152873883-601b29a3-3ac2-4aab-97a3-e245e0c484c3.mov
> feat(StatusQ.Components): Adding StatusWizardSteper component

- src/StatusQ/Components/StatusListItem.qml
Needed for: https://github.com/status-im/status-desktop/pull/4727
> refactor(StatusListItem): add highlighted property

- src/StatusQ/Components/StatusChatList.qml
- src/StatusQ/Components/StatusChatListItem.qml
Part of: https://github.com/status-im/status-desktop/issues/4767
> feat(StatusChatList): Highlight chat item at creation time

- src/StatusQ/Controls/StatusPasswordStrengthIndicator.qml
Added new Strength type None and its corresponding state.
> feat(StatusPasswordStrengthIndicator): Updates in component

- src/StatusQ/Components/StatusLetterIdenticon.qml
- src/StatusQ/Components/StatusSmartIdenticon.qml
For desktop task #4956 the letter identicon displayed inside
the StatusSmartIdenticon should be of 2 characters and not 1.
> feat(StatusLetterIdenticon): Added charCount property in StatusLetterIdenticon

- sandbox/controls/ListItems.qml
- src/StatusQ/Components/StatusListItem.qml
- src/StatusQ/Components/StatusListItemTag.qml
Tags are meant to be dynamic, so switch from static declaration to a model
> fix(@StatusListItem): Use tags model

- sandbox/controls/ListItems.qml
- sandbox/main.qml
- sandbox/pages/StatusColorSelectorGridPage.qml
- sandbox/pages/StatusInputPage.qml
- src/StatusQ/Components/StatusChatList.qml
- src/StatusQ/Components/StatusChatListItem.qml
- src/StatusQ/Components/StatusLetterIdenticon.qml
- src/StatusQ/Components/StatusSmartIdenticon.qml
- src/StatusQ/Controls/StatusBaseInput.qml
- src/StatusQ/Controls/StatusColorRadioButton.qml
- src/StatusQ/Controls/StatusColorSelectorGrid.qml
- src/StatusQ/Controls/StatusInput.qml
- src/StatusQ/Controls/qmldir
- src/StatusQ/Core/StatusIconSettings.qml
- src/StatusQ/Core/Utils/Emoji.qml
- src/StatusQ/Core/Utils/Utils.qml
1. StatusChatListItem (only updated emoji and moved it under icon settings)
2. StatusListItem
3. StatusInput
> feat: Add emoji support

- sandbox/controls/ListItems.qml
- sandbox/demoapp/StatusAppCommunityView.qml
- sandbox/demoapp/data/Models.qml
- src/StatusQ/Components/StatusChatListItem.qml
- src/StatusQ/Components/StatusLetterIdenticon.qml
- src/StatusQ/Components/StatusListItem.qml
- src/StatusQ/Components/StatusSmartIdenticon.qml
- src/StatusQ/Controls/StatusIdenticonRing.qml
- src/StatusQ/Core/StatusIconSettings.qml
- src/StatusQ/Core/StatusIdenticonRingSettings.qml
Add various of changes required by emojiHash and identiconRing integration: https://github.com/status-im/status-desktop/issues/4782
> Add various of changes required by emojiHash and identiconRing integration

- sandbox/pages/StatusInputPage.qml
- src/StatusQ/Controls/StatusBaseInput.qml
- src/StatusQ/Controls/StatusSeedPhraseInput.qml
- src/StatusQ/Controls/qmldir
- statusq.qrc
Closes #567
Also added an example in Inputs page
https://user-images.githubusercontent.com/31625338/157976842-d629dc9a-d8f1-43b9-af7f-6040ca120d9f.mov
> feat(StatusQ/Controls): Adding StatusSeedPhraseInput control

- src/StatusQ/Components/StatusChatListItem.qml
- src/StatusQ/Components/StatusLetterIdenticon.qml
- src/StatusQ/Components/StatusListItemBadge.qml
- src/StatusQ/Components/StatusSmartIdenticon.qml
- src/StatusQ/Core/StatusIconSettings.qml
- src/StatusQ/Core/Utils/Emoji.qml
Also enables emojjis in the ChatIdentifier and chat header
> feat(StatusIconSetting): add emojiSize setting for icons

- src/StatusQ/Controls/StatusSeedPhraseInput.qml
Relates to: https://github.com/status-im/status-desktop/issues/4955
> fix(SeedPhraseInput): fix lost focus after typing one character

- src/StatusQ/Controls/StatusPasswordStrengthIndicator.qml
Added new `onValueChanged` condition if bar value is 0 --> Strength.None.
> fix(StatusPasswordStrengthIndicator): Added new `onValueChanged` condition

- sandbox/pages/StatusInputPage.qml
- src/StatusQ/Controls/StatusBaseInput.qml
- used RowLayout for position management which simplifies code a lot
- fixed implicitHight for "Multiline with max/min" scenario, see video:
https://user-images.githubusercontent.com/33099791/159000891-10a234dc-457a-4708-b68f-e274a9fab123.mp4
> refactor(StatusBaseInput): use RowLayout for position management

- src/StatusQ/Components/StatusChatListItem.qml
- src/StatusQ/Components/StatusLetterIdenticon.qml
- src/StatusQ/Controls/StatusBaseInput.qml
The emoji wasn't centered correctly on Windows
Fixes #5045
> fix(StatusLetterIdenticon): fix emoji positioning

- .github/pull_request_template.md
> chore: add check for dark and light theme to PR template

- src/StatusQ/Controls/StatusSeedPhraseInput.qml
> fix(StatusSeedPhraseInput): Increased suggestion match chars to 4

- src/StatusQ/Controls/StatusInput.qml
It makes it work with layouts correctly.
Required by: https://github.com/status-im/status-desktop/pull/5141
> fix(StatusInput): add implicitHeight

- .gitignore
- tests/TestControls/CMakeLists.txt
- tests/TestControls/StatusQ/TestHelpers/TestUtils.qml
- tests/TestControls/StatusQ/TestHelpers/qmldir
- tests/TestControls/TestHelpers/CMakeLists.txt
- tests/TestControls/TestHelpers/MonitorQtOutput.cpp
- tests/TestControls/TestHelpers/MonitorQtOutput.h
- tests/TestControls/main.cpp
- tests/TestControls/tst_test-StatusBaseInput.qml
- tests/TestControls/tst_test-StatusInput.qml
- tests/readme.md
Adds regression test for #584
Add test helpers to monitor QML output using a declarative approach.
Improves the QML tests structure.
> test(StatusInput): add regression unit test for StatusInput

- sandbox/controls/ListItems.qml
- src/StatusQ/Components/StatusExpandableItem.qml
- src/StatusQ/Components/StatusListItem.qml
- [x ] follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x ] update sandbox app
- [ x] test changes in both light and dark theme?
- [ x] test changes in [status-desktop](https://github.com/status-im/status-desktop)
> feat(StatusListItem): Added new tags inline in the StatusListItem

- src/code-examples.md
- src/contributing.md
Developer targeted checklist and reminders to cover the most common source of errors and tech-debt (maintenance burden).
In environments like UX and UI, it is impossible to consider and follow the implications of all the variables and dependencies. This PR attempts to create checklists that guide QML/Qt developers in their work.
The plan is to add reminders and entries for the common source of oversight found in development which hopefully will help newcomers and seasoned `StatusQ` developers.
If the page/file grows too much, it can be split into sections and addressed in other files by link indirection.
> doc(General): initial proposal on developer documentation and checklists

- sandbox/demoapp/data/Models.qml
- src/StatusQ/Components/StatusChatList.qml
- src/StatusQ/Components/StatusChatListItem.qml
- src/StatusQ/Components/StatusLetterIdenticon.qml
- src/StatusQ/Components/StatusSmartIdenticon.qml
- src/StatusQ/Controls/StatusChatInfoButton.qml
- src/StatusQ/Controls/StatusIconTabButton.qml
- src/StatusQ/Controls/StatusIdenticonRing.qml
- src/StatusQ/Core/StatusIconSettings.qml
- src/StatusQ/Popups/StatusSearchLocationMenu.qml
needed by: https://github.com/status-im/status-desktop/pull/5284
---
> fix: add various fixes/improvements to identicons

- src/StatusQ/Components/StatusListItem.qml
Part of: https://github.com/status-im/status-desktop/issues/5350
> fix(StatusListItem): Show emoji if exist

- src/StatusQ/Popups/StatusSearchLocationMenu.qml
fixes https://github.com/status-im/status-desktop/issues/5139
> fix(StatusSearchLocationMenu): removed dimming from submenus

- src/contributing.md
Follow up on the PR comment https://github.com/status-im/status-desktop/pull/5549#issuecomment-1099468321
> doc(contributing.md): add pixel miss-alignment recommendation

- src/StatusQ/Controls/StatusBaseInput.qml
> fix(StatusBaseInput): Implement cursor as per designs

- src/StatusQ/Controls/StatusBaseInput.qml
> fix(StatusBaseInput): Fixed border color on active focus loss

- src/StatusQ/Components/StatusWizardStepper.qml
- src/StatusQ/Controls/StatusBaseInput.qml
- src/StatusQ/Controls/StatusSelectableText.qml
status-desktop PR https://github.com/status-im/status-desktop/pull/5558
> Small fixes for the contact verification PR

- src/StatusQ/Controls/StatusSwitchTabBar.qml
- src/StatusQ/Controls/StatusSwitchTabButton.qml
- src/StatusQ/Core/Theme/StatusDarkTheme.qml
- src/StatusQ/Core/Theme/StatusLightTheme.qml
- src/StatusQ/Core/Theme/ThemePalette.qml
For https://github.com/status-im/status-desktop/issues/5612
> fix(StatusSwitchTabBar): Update and unify colors of tabBar

- src/StatusQ/Components/StatusTagSelector.qml
This is needed fo https://github.com/status-im/status-desktop/issues/5641
- [ x] follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ x] test changes in [status-desktop](https://github.com/status-im/status-desktop)
> Create new chat input is single line

- src/StatusQ/Components/StatusBadge.qml
- src/StatusQ/Components/StatusChatListAndCategories.qml
- src/StatusQ/Components/StatusChatListCategoryItem.qml
- src/StatusQ/Components/StatusChatListItem.qml
- src/StatusQ/Components/StatusChatToolBar.qml
- src/StatusQ/Components/StatusToastMessage.qml
- src/StatusQ/Components/StatusWizardStepper.qml
- src/StatusQ/Controls/StatusBaseInput.qml
- src/StatusQ/Controls/StatusInput.qml
- src/StatusQ/Controls/StatusPasswordStrengthIndicator.qml
- src/StatusQ/Controls/StatusWalletColorSelect.qml
- src/StatusQ/Controls/Validators/StatusAddressOrEnsValidator.qml
- src/StatusQ/Controls/Validators/StatusAddressValidator.qml
- src/StatusQ/Controls/Validators/StatusAsyncEnsValidator.qml
- src/StatusQ/Controls/Validators/StatusAsyncValidator.qml
- src/StatusQ/Controls/Validators/StatusFloatValidator.qml
- src/StatusQ/Controls/Validators/StatusIntValidator.qml
- src/StatusQ/Controls/Validators/StatusUrlValidator.qml
- src/StatusQ/Controls/Validators/StatusValidator.qml
- src/StatusQ/Core/StatusBaseText.qml
- src/StatusQ/Platform/StatusMacNotification.qml
- src/StatusQ/Popups/StatusModal.qml
- src/StatusQ/Popups/StatusSearchLocationMenu.qml
- src/StatusQ/Popups/StatusSearchPopup.qml
issue: status-im/status-desktop#4544
> chore(translations): add missing qsTrs

- src/StatusQ/Components/StatusTagSelector.qml
Fixes: https://github.com/status-im/status-desktop/issues/5642
> fix(StatusTagSelector): Updated names list filtering

- src/StatusQ/Core/Utils/Emoji.qml
Needed for status-im/status-desktop#5259
* Introduced `format] argument for `parse` function
* New `iconId(text)` function
> feat(Emoji): Functions improvements

- src/StatusQ/Controls/StatusSlider.qml
Fixes #644
https://user-images.githubusercontent.com/25482501/168081101-da5867e7-4186-4390-a2a7-750bd338e414.mov
> fix(StatusSlider): Fixed background behavior

- src/StatusQ/Controls/StatusSeedPhraseInput.qml
> fix(StatusSeedPhraseInput): ensure suggested item has correct text color

- sandbox/demoapp/StatusAppChatView.qml
- src/StatusQ/Components/StatusChatInfoToolBar.qml
- src/StatusQ/Components/StatusChatListAndCategories.qml
Needed for https://github.com/status-im/status-desktop/issues/5211
> fix(StatusChatList): Fixed alignment in left column

- src/StatusQ/Components/StatusTagSelector.qml
Closes: https://github.com/status-im/status-desktop/issues/5220
> fix(StatusTagSelector): Fix mouse hover

- sandbox/demoapp/CreateChatView.qml
- sandbox/demoapp/StatusAppChatView.qml
- sandbox/demoapp/StatusAppCommunityView.qml
- sandbox/demoapp/data/Models.qml
- src/StatusQ/Components/StatusMemberListItem.qml
- src/StatusQ/Components/StatusTagSelector.qml
Fixes https://github.com/status-im/status-desktop/issues/5625
> feat(StatusTagSelector): Replaced member delegate w/ StatusMemberLisItm

- src/StatusQ/Components/StatusListItem.qml
Needed for: https://github.com/status-im/status-desktop/issues/5212
> fix(StatusListItem): added mouse obj parameter in clicked signal

- sandbox/controls/Buttons.qml
- sandbox/main.qml
- sandbox/pages/StatusColorSpacePage.qml
- sandbox/qml.qrc
- src/StatusQ/Components/StatusColorSpace.qml
- src/StatusQ/Components/qmldir
- src/StatusQ/Controls/StatusColorSelectorGrid.qml
- src/StatusQ/Popups/StatusColorDialog.qml
- src/StatusQ/Popups/qmldir
- statusq.qrc
https://user-images.githubusercontent.com/2522130/168869386-cdb0a49c-fd4f-49c7-a34a-c9946bfac70f.mp4
> feat(StatusColorSpace): impl color space component

- sandbox/controls/Controls.qml
- src/StatusQ/Controls/StatusLabeledSlider.qml
- src/StatusQ/Controls/StatusSlider.qml
- src/StatusQ/Controls/qmldir
- statusq.qrc
> feat(StatusLabeledSlider): add ability to decorate sliders and slider, decorated with labels

- src/StatusQ/Controls/StatusBaseInput.qml
also added view icon
Needed for: https://github.com/status-im/status-desktop/issues/4918
> feat(StatusBaseInput): disabled mouse area when input is disabled

- src/StatusQ/Controls/StatusBaseInput.qml
- src/StatusQ/Controls/StatusInput.qml
- chore(StatusInput): use layouts for elements positioning  
It removes complexity and fixes StatusInput to follow the size assigned
by the client.
- chore(StatusBaseInput): expose placeholder as alias
needed by: https://github.com/status-im/status-desktop/pull/5882
> input improvements

- src/StatusQ/Core/StatusBaseText.qml
> chore(StatusBaseText): add theme aware default color

- src/StatusQ/Components/StatusTagSelector.qml
Closes https://github.com/status-im/status-desktop/issues/5954
> fix(StatusTagSelector): Fixed Layout issues when shrinking

- src/StatusQ/Controls/StatusAccountSelector.qml
- src/StatusQ/Controls/StatusAssetSelector.qml
- src/StatusQ/Core/Utils/Utils.qml
address
Add chain id parameter and update attribute
> feat(@StatusAssetSelector): Use asset selector per symbol and not

- src/StatusQ/Components/StatusChatToolBar.qml
- src/StatusQ/Controls/StatusActivityCenterButton.qml
- src/StatusQ/Controls/qmldir
> feat(StatusActivityCenterButon): Introduce `StatusActivityCenterButton`

- src/StatusQ/Components/StatusCommunityCard.qml
Fixes https://github.com/status-im/status-desktop/issues/6206
> fix(StatusCommunityCard): Added implicit width and height

- src/StatusQ/Core/StatusAnimatedStack.qml
- src/StatusQ/Core/qmldir
- src/StatusQ/Popups/StatusModal.qml
- src/StatusQ/Popups/StatusStackModal.qml
- src/StatusQ/Popups/qmldir
https://user-images.githubusercontent.com/2522130/175529911-6954041e-060a-4712-a38f-cbdf493f9c1f.mov
> feat(StatusStackModal): Component to replace nested StatusModals

- sandbox/demoapp/ChatChannelView.qml
- sandbox/demoapp/data/Models.qml
- src/StatusQ/Components/StatusContactVerificationIcons.qml
- src/StatusQ/Components/StatusMemberListItem.qml
- src/StatusQ/Components/StatusMessage.qml
- src/StatusQ/Components/StatusMessageDetails.qml
- src/StatusQ/Components/StatusTagSelector.qml
- src/StatusQ/Components/private/statusMessage/StatusMessageHeader.qml
We decided as a team that isMutualContact was to be renamed isContact
Here is the Desktop PR updating to the breaking change: https://github.com/status-im/status-desktop/pull/6375
> refactor(isContact): rename isMutualContact to isContact

- doc/src/statusqcore.qdoc
- sandbox/pages/StatusPopupMenuPage.qml
- src/StatusQ/Core/StatusFontSettings.qml
- src/StatusQ/Core/qmldir
- src/StatusQ/Popups/StatusMenuItem.qml
- src/StatusQ/Popups/StatusMenuItemDelegate.qml
- statusq.qrc
> feat(StatusFontSettings): Add StatusFontSettings component to change StatusMenuItems font attributes

- src/StatusQ/Controls/StatusActivityCenterButton.qml
Closes https://github.com/status-im/status-desktop/issues/6350
> fix(StatusActivityCenterButton): fixed actvity icon position

- sandbox/demoapp/StatusAppChatView.qml
As part of https://github.com/status-im/status-desktop/issues/6352
> fix(StatusAppChatView): Updated layout based on new designs

- sandbox/demoapp/CreateChatView.qml
As part of https://github.com/status-im/status-desktop/issues/6354
> fix(CreateChatView): fixed no contacts text alignment

- sandbox/controls/Popups.qml
- src/StatusQ/Controls/StatusAssetSelector.qml
- src/StatusQ/Controls/StatusFloatingButtonsSelector.qml
> fix(StatusFloatingButtonsSelector): Fix the issue of floating buttons having incorrect color in Dark theme

- src/StatusQ/Components/StatusBadge.qml
- src/StatusQ/Controls/StatusActivityCenterButton.qml
Closes https://github.com/status-im/status-desktop/issues/6350
> fix(StatusActivityCenterButton): updated offset values

- src/StatusQ/Components/StatusListItem.qml
plus added/updated icon assets
Needed for https://github.com/status-im/status-desktop/issues/6494
> feat(StatusListItem): adding title text icon

- src/StatusQ/Controls/StatusScrollBar.qml
- src/StatusQ/Core/StatusGridView.qml
- src/StatusQ/Core/StatusListView.qml
- src/StatusQ/Core/StatusScrollView.qml
- src/StatusQ/Core/qmldir
For https://github.com/status-im/status-desktop/pull/6456
> feat(StatusListView): Add tuned ListView component and fix ScrollView srollbars

- src/StatusQ/Controls/StatusChatInfoButton.qml
> test(StatusChatInfoButton): add objectName to StatusChatInfoButton

- src/StatusQ/Controls/StatusChatInfoButton.qml
- src/StatusQ/Popups/StatusMenuItemDelegate.qml
> test(StatusMenuItemDelegate): add objectName property for tests

- src/StatusQ/Components/StatusChatToolBar.qml
> test(StatusChatToolBar): add object name for tests

- src/StatusQ/Controls/Validators/StatusMinLengthValidator.qml
StatusMinLengthValidator checks also if the text contains only whitespaces.
Fixes #6304
> fix(StatusMinLengthValidator): Check if the text contains only whitespaces

- sandbox/demoapp/StatusAppChatView.qml
- sandbox/examples/FilteringSorting.qml
- sandbox/pages/StatusCommunityTagsPage.qml
- sandbox/pages/StatusInputPage.qml
- src/StatusQ/Components/StatusCard.qml
- src/StatusQ/Components/StatusListPicker.qml
- src/StatusQ/Components/private/statusMessage/StatusEditMessage.qml
- src/StatusQ/Controls/StatusBaseInput.qml
- src/StatusQ/Controls/StatusInput.qml
- src/StatusQ/Popups/StatusSearchPopup.qml
- tests/TestControls/tst_test-StatusInput.qml
> fix(StatusInput): fixing various layout issues

- src/assets/img/icons/status-logo-icon.svg
> fix: Move status logo to icons folder needed un the ReceiveModal

- sandbox/main.qml
- sandbox/pages/StatusAssetSelectorPage.qml
- src/StatusQ/Controls/StatusAssetSelector.qml
- src/StatusQ/Controls/StatusSelect.qml
- src/StatusQ/Controls/qmldir
> Revert "chore: Remove StatusAssetSelector from StatusQ"

- sandbox/pages/StatusListPickerPage.qml
- src/StatusQ/Components/StatusListPicker.qml
- src/StatusQ/Core/Utils/Emoji.qml
closes: https://github.com/status-im/status-desktop/issues/6500
> Make StatusListPicker work with backend models

- src/StatusQ/Components/StatusListItem.qml
> test(StatusListItem): add objectName

- src/StatusQ/Controls/StatusFloatingButtonsSelector.qml
> feat(@StatusFloatingButtonsSelector): expose repeater

- src/StatusQ/Popups/Dialog/StatusDialog.qml
- src/StatusQ/Popups/Dialog/StatusDialogBackground.qml
- src/StatusQ/Popups/Dialog/qmldir
feat(StatusDialog): Add background color property to make the dialog background customizable
> feat(StatusDialog): Add background color property to make the dialog background customizable

- src/StatusQ/Core/Utils/Emoji.qml
- src/StatusQ/Core/Utils/qmldir
Needed for: https://github.com/status-im/status-desktop/issues/6729
> fix(Utils): moved emojilists.js instance inside Emoji singleton

- src/StatusQ/Controls/StatusCommunityTag.qml
For https://github.com/status-im/status-desktop/pull/6770
> fix(StatusCommunityTag): Polish text and icon sizings

- src/StatusQ/Popups/StatusSearchPopup.qml
> fix(StatusSearchPopup): Fix `forceActiveFocus` method

- sandbox/DemoApp.qml
- sandbox/controls/Layout.qml
- sandbox/controls/Popups.qml
- sandbox/demoapp/DemoCommunityDetailModal.qml
- sandbox/demoapp/StatusAppChatView.qml
- src/StatusQ/Controls/StatusBackButton.qml
- src/StatusQ/Controls/qmldir
- src/StatusQ/Popups/StatusModal.qml
- src/StatusQ/Popups/StatusStackModal.qml
Closes: https://github.com/status-im/status-desktop/issues/6727
> feat(StatusQ/Controls): introducing StatusBackButton

- src/StatusQ/Components/StatusSmartIdenticon.qml
> test(StatusSmartIdenticon): add objectName for tests

- sandbox/sandboxapp.h
> fix(handler): Remove handler include from sandbox

- src/StatusQ/Components/StatusImageCropPanel.qml
- src/StatusQ/Controls/StatusSlider.qml
- update StatusSlider handle and background positioning
Needed for https://github.com/status-im/status-desktop/issues/6835
Required by https://github.com/status-im/status-desktop/pull/6872
> fix(StatusImageCropPanel) adjust Image Crop component

- src/StatusQ/Components/StatusImageCropPanel.qml
Needed for status-im/status-desktop#6835
Required by status-im/status-desktop#6872
> fix(StatusImageCropPanel) add margins to crop area

- sandbox/controls/Controls.qml
- src/StatusQ/Controls/StatusCheckBox.qml
`leftSideCheckbox` determines whether to display check box on the left or right side, defaulted to left
> feat(StatusCheckbox): introduced new `leftSide` prop

- src/StatusQ/Components/StatusChatListAndCategories.qml
For https://github.com/status-im/status-desktop/pull/7010
Just object names for testing
> test(StatusChatListAndCategories): Add object names

- src/StatusQ/Components/StatusChatListAndCategories.qml
> test(StatusChatListAndCategories) add object names for testing

- src/StatusQ/Layout/StatusAppNavBar.qml
- src/StatusQ/Popups/StatusSearchPopup.qml
> test(StatusSearchPopup): add object names for tests

- src/StatusQ/Controls/StatusComboBox.qml
> feat(@StatusComboBox): expose inner objectName property

- src/StatusQ/Popups/StatusSearchPopup.qml
> test(StatusSearchPopup): add object name for tests

- sandbox/demoapp/CreateChatView.qml
Add fix from https://github.com/status-im/status-desktop/pull/7077 to
demoapp
> fix(CreateChatView): update sandbox demoapp

- src/StatusQ/Controls/StatusItemPicker.qml
- src/StatusQ/Controls/StatusRadioButton.qml
Needed for https://github.com/status-im/status-desktop/issues/6337
> Added properties in `StatusItemPicker` and variant to `StatusRadioButton`. Needed for desktop issue #6337

- src/StatusQ/Controls/StatusBaseInput.qml
- src/StatusQ/Controls/StatusSelectableText.qml
- src/StatusQ/Core/StatusScrollView.qml
- src/StatusQ/Core/Utils/Utils.qml
Required for https://github.com/status-im/status-desktop/issues/7093
> feat(StatusScrollView): add ensureVisible function

- src/StatusQ/Components/StatusChatListCategory.qml
For https://github.com/status-im/status-desktop/pull/7156
> fix(StatusChatListCategory): Add alias to category item for squish tests

- src/StatusQ/Controls/StatusSelectableText.qml
> fix(StatusSelectableText): add missing Utils import

- sandbox/pages/StatusInputPage.qml
- src/StatusQ/Controls/StatusPasswordInput.qml
- src/StatusQ/Controls/qmldir
- src/statusq.qrc
`StatusPasswordInput` is a wrapper around  `TextField` with an option to display signing phrase.
> feat(Controls): introduce `StatusPasswordInput`

- sandbox/controls/ListItems.qml
- src/StatusQ/Components/StatusListItem.qml
feat(StatusListItem): Added new properties to handle inline tags needed in the wallet section
> feat(StatusListItem): Added new properties to handle inline tags needed in the wallet section

- src/StatusQ/Components/StatusChatList.qml
- src/StatusQ/Components/StatusChatListItem.qml
- src/StatusQ/Components/StatusSmartIdenticon.qml
> feat(StatusChatListItem): add online badge

- src/StatusQ/Components/StatusMessage.qml
Fixes https://github.com/status-im/status-desktop/issues/7301
> fix(StatusMessage): adjust text alignment

- sandbox/pages/StatusPinInputPage.qml
- src/StatusQ/Controls/StatusPinInput.qml
Two new props exposed so we can sed an extra spacing for every N-th item.
- `additionalSpacingOnEveryNItems` - determines for which item to add an extra space
- `additionalSpacing` - determines the value of extra space which will be added
> feat(StatusPinInput): additional spacing for every N-th digit

- src/StatusQ/Components/StatusChartPanel.qml
> fix(StatusChartPanel): fix #893 PR comments

- sandbox/pages/StatusChartPanelPage.qml
- src/StatusQ/Components/StatusChartPanel.qml
> fix(StatusChartPanel): updated left spacing

- sandbox/controls/Buttons.qml
- src/StatusQ/Controls/StatusBaseButton.qml
> fix(StatusBaseButton): align text to horizontal center

- src/StatusQ/Components/private/statusMessage/StatusPinMessageDetails.qml
Fixes status-im/status-desktop#7305
> fix(StatusPinMessageDetails): correct spacing

- sandbox/demoapp/ChatChannelView.qml
- sandbox/demoapp/data/Models.qml
- src/StatusQ/Components/StatusMessage.qml
- src/StatusQ/Components/StatusMessageSenderDetails.qml
- src/StatusQ/Components/private/statusMessage/StatusMessageHeader.qml
- src/StatusQ/Components/private/statusMessage/StatusMessageReply.qml
StatusMessageSenderDetails contains only displayName and secondaryName. Correct values are delivered by a model.
Issue #7241
> fix(StatusMessageSenderDetails): Simplify StatusMessageSenderDetails

- src/StatusQ/Layout/StatusSectionLayout.qml
> hotfix(StatusSectionLayout): Fix notificationCount availability

- sandbox/demoapp/StatusAppCommunitiesPortalView.qml
- src/StatusQ/Components/StatusToolBar.qml
- src/StatusQ/Layout/StatusSectionLayout.qml
Needed for https://github.com/status-im/status-desktop/issues/7312
> (StatusSectionLayout): Added back button in StatusChatToolbar 
