status-im/StatusQ

README.md, sandbox/Others.qml, sandbox/main.qml, sandbox/qml.qrc, src/StatusQ/Components/StatusLoadingIndicator.qml, src/StatusQ/Components/qmldir
A `StatusIcon` that rotates infinitely and can be used for indicating
pending states.
Usage:
```
StatusLoadingIndicator {
width: 24 // default: 17
height: 24 // default: 17
color: "red" // default: loading asset color
}
```
Closes #7
=> feat(Components): introduce StatusLoadingIndicator

src/StatusQ/Core/Theme/StatusDarkTheme.qml, src/StatusQ/Core/Theme/StatusLightTheme.qml, src/StatusQ/Core/Theme/ThemePalette.qml
Turns out, even though we only use one and the same `font.family` name
throughout our components (namely `Inter` and/or `InterStatus`),
`font.weight` properties set to anything other than `Font.Normal` (which is the default),
will not apply unless all font weights have actually been loaded.
Unfortunately we can put a `FontLoader` as direct child in a `ThemePalette`
so we have to make it actual properties.
These properties aren't really used anywhere and merely serve as a place
to load font assets.
Fixes #30
=> fix(Core.Theme): ensure all font weight are available

sandbox/Others.qml, src/StatusQ/Components/StatusLetterIdenticon.qml, src/StatusQ/Components/qmldir
This introduces the `StatusLetterIdenticon` component to StatusQ.
Usage:
```
StatusLetterIdenticon {
name: "#status"
}
```
Closes #28
=> feat(Components): introduce StatusLetterIdenticon

src/StatusQ/Core/Theme/ThemePalette.qml
Status color palettes don't specify a solid black and white that stay
black and white in both themes.
This commit introduces `black` and `white` as solid colors to `ThemePalette`
so they are automatically inherited in all built-in and custom themes.
=> feat(Core.Theme): expose solid black and white on `ThemePalette`

sandbox/Others.qml, src/StatusQ/Components/StatusBadge.qml, src/StatusQ/Components/qmldir
This component can be used to render badges with additional information
as seen in the navbar tab buttons and menu items.
Here's how it can be used:
```
StatusBadge {
value: 2
}
```
By default and based on value, StatusBadge will change its width.
If no value is provided, it renders as badge indicator as seen in the profile
tab button.
Closes #15
=> feat(Components): introduce StatusBadge component

README.md, sandbox/Controls.qml, sandbox/main.qml, sandbox/qml.qrc, src/StatusQ/Controls/StatusIconTabButton.qml, src/StatusQ/Controls/qmldir
This adds the `StatusIconTabButton` componoent to `StatusQ` with some slight
adjustments:
- removes `iconColor` in favour of `icon.color`
- removes `disabledColor` (main reason being that we don't show disabled buttons of this type)
This button handles various cases:
1. Icon tab buttons - An icon button used in Status Desktop for different sections
2. Letter identicon button - Used for community sections that don't have a profile picture
3. Image icon button - Used for community sections that do have a profile picture
Which type is rendered depends on the configuration of the component as shown
in the usage.
Usage:
```
import StatusQ.Controls 0.1
// When `icon.name` is set, it renders a `StatusIcon` button
StatusIconTabButton {
icon.name: "chat"
}
// When `icon.source` is set, it renders …
```
=> feat(Core.Controls): introduce StatusIconTabButton component 

sandbox/Controls.qml, src/StatusQ/Controls/StatusToolTip.qml, src/StatusQ/Controls/qmldir
This moves the `StatusToolTip` component into `StatusQ` and applies some of
the changes done by @jrainville in https://github.com/status-im/status-desktop/pull/2447.
Usage:
```
import StatusQ.Controls 0.1
Button {
text: "Hover me!"
StatusToolTip {
visible: parent.hovered
text: "Top"
orientation: StatusToolTip.Orientation.Top // default: Top
}
}
```
Closes #14
=> feat(Controls): introduce StatusToolTip component

sandbox/Controls.qml, src/StatusQ/Controls/StatusNavBarTabButton.qml, src/StatusQ/Controls/qmldir
This component is used to render application tabs in the application
nav bar that is yet to be implemented.
`StatusNavBarTabButton` is a composition of `StatusIconTabButton`, `StatusToolTip`
and `StatusBadge` and exposes each of these to enable customization.
Usage:
```
StatusNavBarTabButton {
checked: true/false // whether or not it's 'active'
name: "string" // used to render a `StatusLetterIdenticon`
badge.value: 30 // `StatusBadge` is exposed as `badge`
tooltip.text: "Some tooltip" // `StatusTooltip` is exposed as `tooltip`
icon.name: "message" // Behaves exactly like `StatusIconTabButton.icon`
}
```
Closes #17
=> feat(Controls): introduce StatusNavBarTabButton

sandbox/Layout.qml, sandbox/main.qml, src/StatusQ/Core/Theme/StatusDarkTheme.qml, src/StatusQ/Core/Theme/StatusLightTheme.qml, src/StatusQ/Core/Theme/ThemePalette.qml, src/StatusQ/Layout/StatusAppNavBar.qml, src/StatusQ/Layout/qmldir
This commit introduces a new `StatusAppNavBar` component that can be used
to create a Status application's tab bar for dedicated tab sections such as
chat, profile, wallet etc.
The component is build in a way that it support declarative and imperative usage
where necessary.
In its most simple form, a `StatusAppNavBar` comes with a single tab button
for the chat section. Such button has to be of type `StatusNavBarTabButton`:
```qml
import StatusQ.Layout 0.1
StatusAppNavBar {
navBarChatButton: StatusNavBarTabButton {
icon.name: "chat"
badge.value: 33
badge.visible: true
tooltip.text: "Chat"
}
}
```
In addition, it's possible to specify a list of `StatusNavBarTabButton` for
other sections of the application using the `navBarTabButtons` property:
```qml
StatusAppNavBar {
...
navBarTabButtons: …
```
=> feat(Layout): introduce StatusAppNavBar

sandbox/main.qml
This is just temporary until #40 lands, but for now it allows for
the scrollable content to be grow which is needed to make pages
with many components usable.
=> fix(sandbox): make scrollview content height grow with content

sandbox/ListItems.qml, sandbox/main.qml, src/StatusQ/Components/StatusListItem.qml, src/StatusQ/Components/qmldir, src/StatusQ/Core/Theme/StatusDarkTheme.qml, src/StatusQ/Core/Theme/StatusLightTheme.qml, src/StatusQ/Core/Theme/ThemePalette.qml
This introduces a base list item component that is used in many different
places across Status Desktop. The component is configurable and allows for
child component customization.
Usage:
```qml
StatusListItem {
title: "Title"
}
StatusListItem {
title: "Title"
subTitle: "Subtitle"
}
StatusListItem {
title: "Title"
subTitle: "Subtitle"
icon.name: "info"
}
StatusListItem {
title: "Title"
subTitle: "Subtitle"
image.source: "..."
}
StatusListItem {
title: "Title"
subTitle: "Subtitle"
image.source: "..."
label: "Some label"
}
StatusListItem {
title: "Title"
subTitle: "Subtitle"
icon.name: "info"
label: "Some label"
components: [
StatusButton {
text: "Button"
size: StatusBaseButton.Size.Small
}
...
]
}
```
Closes #19
=> feat(Components): introduce `StatusListItem` component

sandbox/ListItems.qml, src/StatusQ/Components/StatusNavigationListItem.qml, src/StatusQ/Components/qmldir, src/StatusQ/Core/Theme/StatusDarkTheme.qml, src/StatusQ/Core/Theme/StatusLightTheme.qml, src/StatusQ/Core/Theme/ThemePalette.qml
This introduces the `StatusNavigationListItem` that can be used to render
menu navigation items in secondary panels, such as the profile panel.
Usage:
```
StatusNavigationListItem {
title: "Menu Item"
}
StatusNavigationListItem {
title: "Menu Item"
icon.name: "info"
}
StatusNavigationListItem {
title: "Menu Item"
icon.name: "info"
badge.value: 1
}
StatusNavigationListItem {
title: "Menu Item (selected)"
selected: true
icon.name: "info"
badge.value: 1
}
```
Closes #72
=> feat(Components): introduce StatusNavigationListItem

sandbox/Layout.qml, src/StatusQ/Core/Theme/StatusDarkTheme.qml, src/StatusQ/Core/Theme/StatusLightTheme.qml, src/StatusQ/Core/Theme/ThemePalette.qml
`StatusBadge` uses a border with same color as its underlying component
to create "fake space" (see `StatusNavTabButton`).
The color depends on the parent component background and its state,
which the `StatusBadge` doesn't know about by itself, so the border color
has to be set explicity whereever it's desired.
This commit introduces (default) colors for the border based on where
badge is used.
=> feat(StatusBadge): introduce `borderColor` and `hoverBorderColor`

src/StatusQ/Core/Theme/StatusDarkTheme.qml, src/StatusQ/Core/Theme/StatusLightTheme.qml, src/StatusQ/Core/Theme/ThemePalette.qml, src/StatusQ/Layout/StatusAppLayout.qml, src/StatusQ/Layout/qmldir
This introduces a layout component to quickly scaffold a Status Desktop
ui layout.
Usage:
```qml
import StatusQ.Layout 0.1
StatusAppLayout {
appNavBar: StatusAppNavBar { ... }
appView: StackView {
anchors.fill: parent
initialItem: Component { ... }
}
}
```
Closes: #77
=> feat(Layout): introduce StatusAppLayout component

sandbox/Controls.qml, src/StatusQ/Controls/StatusChatInfoButton.qml, src/StatusQ/Controls/qmldir, src/StatusQ/Core/Theme/StatusDarkTheme.qml, src/StatusQ/Core/Theme/StatusLightTheme.qml, src/StatusQ/Core/Theme/ThemePalette.qml
Usage:
```qml
StatusChatInfoButton {
title: "Iuri Matias"
subTitle: "Contact"
icon.color: Theme.palette.miscColor7 // identicon used as fallback when image source isn't available
image.source: "https://pbs.twimg.com/profile_images/1369221718338895873/T_5fny6o_400x400.jpg"
type: StatusChatInfoButton.Type.OneToOneChat // PublicChat | GroupChat | CommunityChat
muted: true // default `false`
pinnedMessagesCount: 1 // default `0`
}
```
Here's what it looks like:
Closes: #79
=> feat(Controls): introduce `StatusChatInfoButton`

sandbox/Layout.qml, src/StatusQ/Components/StatusChatToolBar.qml, src/StatusQ/Components/qmldir
Usage:
```qml
StatusChatToolBar {
chatInfoButton.[...]: ... // StatusChatInfoButton
notificationCount: 1 // default `0`
onChatInfoButtonClicked: ...
onMenuButtonClicked: ...
onNotificationButtonClicked: ...
}
```
This is what it looks like:
Closes #80
=> feat(Components): introduce `StatusChatToolBar`

src/StatusQ/Core/StatusIcon.qml
As discussed in #109, when using the `rotation` property of `StatusIcon`
it seems to just mirror the underlying image source.
It turns out that using `rotation` on the image source is enough to have
the `ColorOverlay` rotate as well. Adding a `rotation` to the overlay will
rotate the source that's already rotated, resulting in a mirrored result.
To fix this, we're removing the additional `rotation` from the overlay.
Fixes #109
=> fix(Core): don't rotate `ColorOverlay` of `StatusIcon`

sandbox/DemoApp.qml, src/StatusQ/Components/StatusChatList.qml, src/StatusQ/Components/StatusChatListItem.qml, src/StatusQ/Components/qmldir
This commit introduce a new `StautsChatList` component that can be used
to render `StatusChatListItem`s, typically for chat and community views.
The component expects a `chatListItems.model` that has the following properties:
```qml
ListModel {
ListElement {
chatId: "0"
name: "#status"
chatType: StatusChatListItem.Type.PublicChat
muted: false
hasUnreadMessages: false
hasMention: false
unreadMessagesCount: 0
iconColor: "blue"
}
...
}
```
It also emits two possible signals:
- `onChatItemSelected(string id)`
- `onChatItemUnmuted(string id)`
Usage:
```qml
StatusChatList {
selectedChatId: "0"
chatListItems.model: demoChatListItems
onChatItemSelected: ...
onChatItemUnmuted: ...
}
```
Closes #100
=> feat(Components): introduce `StatusChatList`

sandbox/DemoApp.qml, sandbox/ListItems.qml, src/StatusQ/Components/StatusChatListCategoryItem.qml, src/StatusQ/Components/qmldir, src/StatusQ/Controls/StatusChatListCategoryItemButton.qml, src/StatusQ/Controls/qmldir, src/StatusQ/Core/Theme/StatusDarkTheme.qml, src/StatusQ/Core/Theme/StatusLightTheme.qml, src/StatusQ/Core/Theme/ThemePalette.qml
This component is used to render chat list categories.
Usage:
```qml
StatusChatListCategoryItem {
title: "Public"
onClicked: opened = !opened
onToggleButtonClicked: opened = !opened
onMenuButtonClicked: ...
onAddButtonClicked: ...
addButton.[...]: ... // StatusChatListCategoryItemButton
menuButton.[...]: ... // StatusChatListCategoryItemButton
toggleButton.[...]: ... // StatusChatListCategoryItemButton
}
```
The button components are exposed so their tooltips can be configured
with (internationalized) app messages.
Closes #117
=> feat(Components): introduce `StatusChatListCategoryItem`

sandbox/DemoApp.qml, src/StatusQ/Components/StatusChatListCategory.qml, src/StatusQ/Components/StatusChatListCategoryItem.qml, src/StatusQ/Components/qmldir, src/StatusQ/Controls/StatusChatListCategoryItemButton.qml, src/StatusQ/Popups/StatusPopupMenu.qml
A component used to render chat list groups.
Usage:
```qml
StatusChatListCategory {
categoryId: ...
name: "Public"
opened: true // default `true`
addButton.[...]: ... // `StatusChatListCategoryItemButton`
menuButton.[...]: ... // `StatusChatListCategoryItemButton`
toggleButton.[...]: ... // `StatusChatListCategoryItemButton`
chatList.chatListItems.model: ... // `chatsList` is a `StatusChatList`
chatList.selectedChatId: ...
chatList.onChatItemSelected: ...
popupMenu: StatusPopupMenu {
...
}
}
```
Closes #123
=>  feat(Components): introduce `StatusChatListCategory`

sandbox/DemoApp.qml, src/StatusQ/Components/StatusChatToolBar.qml, src/StatusQ/Controls/StatusFlatRoundButton.qml
This introduces a new `popupMenu` property that can be used to pass
down a `StatusPopupMenu` to `StatusChatToolBar`.
The reason this is done is so that we get control over its `onClosed`
handler, which is used to remove the menu button's `highlighted` state.
The `highlighted` state is activated inside the component as well when
it's clicked.
Existing signals like `menuButtonClicked` still exist and can be leveraged
for further logic.
Closes #125
=> fix(StatusChatToolBar): ensure menu button stays highlighted

src/StatusQ/Layout/StatusAppNavBar.qml
This turned out to be a bug. `model.count` isn't defined on `Repeater`
types.
Also, set `ScrollView` height to `0` if there are not community
tab buttons. This is needed because the columns implicit height
comes with spacing, resulting in some height.
=> fix(StatusAppNavBar): don't rely on `undefined` property

sandbox/DemoApp.qml, src/StatusQ/Controls/StatusIconTabButton.qml, src/StatusQ/Controls/StatusNavBarTabButton.qml
This enables users to apply a `StatusPopupMenu` to the button which automatically
positions itself and takes care of highlighting the activated button.
Usage:
```qml
StatusNavBarTabButton {
...
popupMenu: StatusPopupMenu {
text: qsTr("Invite People")
icon.name: "share-ios"
}
text: qsTr("View Community")
icon.name: "group"
}
text: qsTr("Edit Community")
icon.name: "edit"
}
}
}
```
Closes #137
=> feat(StatusNavBarTabButton): introduce `popupMenu` property

src/StatusQ/Controls/StatusRoundButton.qml
These are needed for some UIs where the icon state may change based on the
user's interaction.
=> feat(StatusRoundButton): add `highlighted` and `icon.rotation` props

sandbox/DemoApp.qml, sandbox/StatusChatInfoToolBarPage.qml, sandbox/main.qml, sandbox/qml.qrc, src/StatusQ/Components/StatusChatInfoToolBar.qml, src/StatusQ/Components/qmldir, src/StatusQ/Controls/StatusChatInfoButton.qml, statusq.qrc
Usage:
```qml
StatusChatInfoToolBar {
chatInfoButton.title: "Cryptokitties"
chatInfoButton.subTitle: "128 Members"
chatInfoButton.image.source: "https://pbs.twimg.com/profile_images/1369221718338895873/T_5fny6o_400x400.jpg"
chatInfoButton.icon.color: Theme.palette.miscColor6
popupMenu: StatusPopupMenu {
text: "Create channel"
icon.name: "channel"
}
text: "Create category"
icon.name: "channel-category"
}
StatusMenuSeparator {}
text: "Invite people"
icon.name: "share-ios"
}
}
}
```
Closes #141
=> feat(Components): introduce `StatusChatInfoToolBar` component

sandbox/DemoApp.qml, sandbox/ListItems.qml, src/StatusQ/Components/StatusChatListCategory.qml, src/StatusQ/Components/StatusChatListCategoryItem.qml
This commit introduces a `showActionButtons` flag that defaults to `false`
and can be used to render the action buttons provided in the chat list category.
This is useful for cases where only admin users should have the right to
create channels inside categories or mutate a category's state.
Settings `showActionButtons: true` will then render the buttons.
Closes #150
=> feat(StatusChatListCategory): introduce flag to show/hide buttons

sandbox/DemoApp.qml, sandbox/ListItems.qml, src/StatusQ/Components/StatusChatListCategory.qml, src/StatusQ/Components/StatusChatListCategoryItem.qml, src/StatusQ/Popups/StatusPopupMenu.qml
Similar to `closeHandler`, StatusPopupMenu can now have a customized `openHandler`
to run custom logic on open.
=> feat(StatusPopupMenu): introduce `openHandler`

sandbox/DemoApp.qml, sandbox/ListItems.qml, src/StatusQ/Components/StatusChatList.qml, src/StatusQ/Components/StatusChatListCategory.qml, src/StatusQ/Components/StatusChatListCategoryItem.qml, src/StatusQ/Popups/StatusPopupMenu.qml
Chat lists can belong to a category inside of communities, so they should
hold a property `categoryId` that represents that. In addition,
this commit introduces a `filterFn` function that can be used to conditionally
show/hide chat list items.
Closes #154
=> feat(StatusChatList): introduce `filterFn` and `categoryId`

sandbox/DemoApp.qml, src/StatusQ/Components/StatusNavigationPanelHeadline.qml, src/StatusQ/Components/qmldir, statusq.qrc
Component to render navigation panel headlines.
Usage:
```qml
StatusNavigationPanelHeadline {
text: "Profile"
}
```
Closes #162
=> feat(Components): introduce `StatusNavigationPanelHeadline`

src/StatusQ/Components/StatusChatListItem.qml
Similar to other controls and components, chat list items can be in a
`highlighted` state, for example when popup menus are active.
Closes #178
=> feat(StatusChatListItem): add `highlighted` property

sandbox/DemoApp.qml, src/StatusQ/Components/StatusChatList.qml, src/StatusQ/Components/StatusChatListAndCategories.qml, src/StatusQ/Components/StatusChatListCategory.qml
Chat list items can open a context on right click as well, so `StatusChatList`
needs to provide an API for users to pass down a `StatusPopupMenu` accordingly.
This is now possible with a dedicated `popupMenu` proporty that can be
used as follows:
```qml
StatusChatList {
...
popupMenu: StatusPopupMenu {
property string chatId
openHandler: function () {
...
}
...
}
...
}
}
```
As will all `popupMenu` properties in StatusQ component, having this explicit API
option enables us to have control over how triggering components (in this case chat
list items) behave when they open a context menu (e.g. keeping them highlighted as long
as the menu is active).
When defining a `chatId` property, `StatusChatList` will hydrate it with the id of
the chat list item that has triggered the …
=> feat(StatusChatList): introduce `popupMenu` property

src/StatusQ/Components/StatusChatList.qml
This property enables users to pass as factory function to `StatusChatList`
component that determines the profile image of a given chat id.
Usage:
```qml
StatusChatList {
...
profileImageFn: function (id) {
// `id` is the model id of the current chat item iterator
return ... // has to return a profile image url
}
}
```
In addition to this property, this commit also makes the component
expect an optional `model.identityImage` in case it's already provided.
That way, `profileImageFn` can be omitted.
Closes #174
=> feat(StatusChatList): introduce `profileImageFn` property

sandbox/DemoApp.qml, src/StatusQ/Components/StatusChatList.qml, src/StatusQ/Components/StatusChatListItem.qml, src/StatusQ/Core/StatusImageSettings.qml, src/StatusQ/Core/Theme/StatusDarkTheme.qml, src/StatusQ/Core/Theme/StatusLightTheme.qml, src/StatusQ/Core/Theme/ThemePalette.qml
This just introduces a new `StatusImageSettings` property `isIdenticon`
which can be used to determine whether a `StatusRoundedImage` should
render with a background + border (which is the case for identicons).
It also updates the `StatusChatList` delegate to consider that property
and have it properly decide how to render the UI.
Closes #173
=> feat(StatusRoundedImage): introduce identicon support

src/StatusQ/Components/StatusChatList.qml
These broke because we were referring to a `highlighted` property that
was wrongly scoped.
Fixes #216
=> fix(StatusChatList): ensure popupMenu closeHandler don't break

sandbox/Popups.qml, src/StatusQ/Popups/StatusModal.qml
As discussed in #237, this is needed for consumers to access content
children from outside `content`.
Usage:
```qml
StatusModal {
id: modal
content: StatusBaseText {
text: "Foo"
}
rightButtons: [
StatusButton {
text: "Change text"
onClicked: {
modal.contentComponent.text = "Bar"
}
}
]
}
```
Fixes #237
=> feat(StatusModal): expose loaded content

sandbox/ListItems.qml, src/StatusQ/Components/StatusListItem.qml, src/StatusQ/Core/StatusIconSettings.qml
This adds support for letter identicons by using the `icon.isLetterIdenticon`
flag:
```qml
StatusListItem {
title: "Some name"
icon.isLetterIdenticon: true
icon.background.color: "orange"
}
```
Closes #239
=> feat(StatusListItem): support letter identicons

sandbox/DemoApp.qml, src/StatusQ/Components/StatusChatList.qml
This is due to a change in how mentions and unread messages are indicated.
See https://github.com/status-im/status-desktop/commit/7fbccec227492c9c9f5188e1088e80304e1101fd for more information.
=> chore: ensure `StatusChatList` receives the proper value for mentions

sandbox/DemoApp.qml, src/StatusQ/Components/StatusChatToolBar.qml
This commit adds the members and search button which are needed for certain
features in Status Desktop. In views where these aren't needed, each button
can be set `visible: false` individually:
```qml
StatusChatToolBar {
...
membersButton.visible: false
searchButton.visible: false
}
```
Closes #243
=> feat(StatusChatToolBar): add members and search button

sandbox/ListItems.qml, src/StatusQ/Components/StatusChatListItem.qml
Also ensure title font weight stays `normal` when item is `muted`.
Closes #258, #259
=> feat(StatusChatListItem): introduce muted badge visuals

src/StatusQ/Popups/statusModal/StatusModalFooter.qml, src/StatusQ/Popups/statusModal/StatusModalHeader.qml
This adds a `StatusModalDivider` to the header and footer so they don't
have to be put into `content` and therefore won't scroll out of the viewport
if the content exceeds the modal height.
The footer divider is only rendered when there's indeed action buttons
provided.
Closes #265
=> feat(StatusModal): render header and footer border by default

src/StatusQ/Components/StatusChatToolBar.qml, src/StatusQ/Controls/StatusToolTip.qml
There's cases where the arrow on the tooltip needs to be repositioned, for example
when the tooltip doesn't fit into the viewport anymore but is centered below a button.
=> feat(StatusToolTip): expose `arrow` for fine-grain control

src/StatusQ/Popups/StatusMenuHeadline.qml, src/StatusQ/Popups/qmldir, statusq.qrc
This component can be used to group different sections within a popup menu.
Usage:
```qml
StatusPopupMenu {
text: "One"
icon.name: "info"
}
StatusMenuHeadline {
text: "Some text"
}
text: "Two"
icon.name: "info"
}
}
```
=> feat(Popups): introduce `StatusMenuHeadline` component

src/StatusQ/Core/Theme/StatusDarkTheme.qml, src/StatusQ/Core/Theme/StatusLightTheme.qml, src/StatusQ/Core/Theme/ThemePalette.qml
There's some usage specific color being added to the chat input (which doesn't live in
StatusQ yet). To make sure we don't lose that change, I'm adding the new
colors to StatusQ theming system and have Status Desktop use it for the time being
until `StatusChatInput` is moved to StatusQ anyways.
=> feat(StatusQ.Theme.Core): introduce theme colors for StatusChatInput

src/StatusQ/Components/StatusChatToolBar.qml
The menu has a CloseOnReleaseOutside policy and so it
was closing and immediately re-opened when the kebab icon
was clicked since it's outside the menu area and also was
calling the popup function of the menu. Added dummy bool
property to detect whether the menu is already closed and
not open it again
Closes #308
=> fix(StatusChatToolBar) Fixing more menu not closing

src/StatusQ/Controls/StatusBaseInput.qml, src/StatusQ/Controls/StatusInput.qml
Prior to this commit, setting `charLimit` on `StatusInput` would only have a visual effect
(rendering the char limit), however it wouldn't actually enforce this limit.
This was by intended behaviour, because we wanted to leave some room
for possible validators to kick in (for example a max length validator).
If however the char limit is enforce, such a validator would never kick in.
There seems to be consensus in the team that the limit should be enforced though.
This commit enables that.
=> feat(StatusBaseInput): enforce `maximumLength` if it's set

sandbox/StatusInputPage.qml, src/StatusQ/Controls/StatusInput.qml, src/StatusQ/Controls/Validators/StatusMinLengthValidator.qml, src/StatusQ/Controls/Validators/StatusValidator.qml, src/StatusQ/Controls/Validators/qmldir, statusq.qrc
Here's what the draft is doing.
There's a new `validators` property that can be used to add validators to `StatusInput` instances, which are executed in the same order:
```qml
StatusInput {
text: "Some value"
validators: [...]
}
```
For convenience StatusQ provides some common validation methods, such as `StatusMinLengthValidator`, StatusMaxLengthValidator` and could be extended to other (e.g. email validation etc):
```qml
StatusInput {
text: "Some value"
validators: [
StatusMinLengthValidator { minLength: 3 }
]
}
```
Validators are executed every time the text of the input changes. They are executed in the same order they have been applied, which enables users to create cascading conditions like "First make sure the value is at least 3 characters long, then make sure it matches a certain …
=> Status form control validator pipeline

src/StatusQ/Controls/StatusBaseInput.qml
These properties can be used to determine whether a user has either
interacted with the form control, or changed its value.
It's also used in initial validation to ensure validation is done but
visually, form controls stay untouched.
Closes #327
=> feat(StatusBaseInput): introduce `dirty` and `pristine` properties

sandbox/DemoApp.qml, sandbox/Models.qml, src/StatusQ/Components/StatusChatList.qml, src/StatusQ/Components/StatusChatListAndCategories.qml, src/StatusQ/Components/StatusChatListItem.qml
This implements drag and drop capabilities of chat items within a `StatusChatList`.
The commit introduces a `DelegateModal` to visually reorder chat items
when they're being dragged and dropped onto a `DropArea`.
To persist the new order of chat items, various signals have been introduced to chat
list related components:
```qml
StatusChatList {
onChatItemReordered: function (id, from, to) {
// ...
}
}
StatusChatListAndCategories {
onChatItemReordered: function (categoryId, chatId, from, to) {
// ...
}
}
```
There's no such API on the `StatusChatListCategory` type because that one already
exposes its underlying `StatusChatList` via `chatList`, which makes the signal available.
Dragging and dropping chat items is disabled by default and needs to be turned on
using the `draggableItems` …
=> feat(StatusChatList): Add drag and drop support of list items

sandbox/Popups.qml, src/StatusQ/Core/StatusModalHeaderSettings.qml, src/StatusQ/Popups/StatusModal.qml, src/StatusQ/Popups/statusModal/StatusImageWithTitle.qml, src/StatusQ/Popups/statusModal/StatusModalHeader.qml
There are now two new properties in `StatusModalHeaderSettings`:
- `titleElide`
- `subTitleElide`
These can be used to configure the `elide` property of both header titles.
The default values for both of them is `Text.ElideRight`.
Closes #353
=> feat(StatusModal): add ability to set elide config of header titles

src/StatusQ/Popups/StatusSearchPopup.qml
This introduces a new API to allow users to provide a function that formats
timestamps in the search results.
```qml
StatusSearchPopup {
formatTimestampFn: function (ts) {
return // formatted ts
}
}
```
Closes #363
=> feat(StatusSearchPopup): add function hook to allow timestamp formatting

src/StatusQ/Popups/StatusModal.qml
Based on Qt docs `contentItem` must have `implicit` sizes.
link to rules: https://doc.qt.io/qt-5/qml-qtquick-controls2-popup.html#popup-sizing
=> fix(StatusModal): Remove self-calculating height

src/StatusQ/Controls/StatusBaseInput.qml
We can't alias the property as `focus` because this is a final readonly
property, so we're introducing a `focussed` property instead.
Closes #373
=> feat(StatusBaseInput): introduce focussed property

src/StatusQ/Layout/StatusAppThreePanelLayout.qml
This margin shows because of `handle` width incuded in `SplitView` width. Handle have `Component` type and can't accessable for getting sizes. I add `magic constant` as hotfix.
Closes: #307
=> fix(StatusAppThreePanelLayout): Fix margin between left and center panels

src/StatusQ/Components/StatusChatListAndCategories.qml
Category tooltip settings were broken in this component due to a mismatching
property name.
This commit fixes it.
=> fix(StatusChatListAndCategories): rely on correct tooltip settings prop

src/StatusQ/Popups/StatusSearchPopup.qml
This is used to enforce focus on the search input when the popup
is opened. In fact users decide to override the search popup's
`onOpened` handler, they still get access to this API to make use of it.
=> feat(StatusSearchPopup): introduce forceActiveFocus API

sandbox/StatusInputPage.qml, src/StatusQ/Controls/StatusBaseInput.qml
This property enables users to load any component into the input field.
This is useful for rendering a "clearable" icon button, simple icons or
even more complex buttons.
Usage:
```qml
StatusBaseInput {
...
component: StatusIcon {
name: "cancel"
color: Theme.palette.dangerColor1
width: 16
}
}
```
The `clearable` property of `StatusBaseInput` also renders and icon button
on the right hand side. With this new feature, `clearable` is just a short-hand
for:
```qml
StatusBaseInput {
...
component: StatusFlatRoundButton {
visible: edit.text.length != 0 &&
statusBaseInput.clearable &&
!statusBaseInput.multiline &&
edit.activeFocus
type: StatusFlatRoundButton.Type.Secondary
width: 24
height: 24
icon.name: "clear"
icon.width: 16
icon.height: 16
icon.color: Theme.palette.baseColor1
onClicked: { …
```
=> feat(StatusBaseInput): introduce `component` property

src/StatusQ/Components/StatusChatList.qml
Ever since we've moved to `DelegateModel` which is passed to the `Repeater`
which was previously aliased as `chatListItems`, we no longer get access to the
`model.itemAt` method. This is because `DelegateModel` doesn't have such a method.
So in order to restore that access, we have to expose `Repeater` additionally.
The reason this method is needed, is so that apps like Status Desktop can update
individual chat list items based on `Connection` events
=> feat(StatusChatList): expose `statusChatListItems` Repeater

src/StatusQ/Components/StatusChatListAndCategories.qml
Category `opened` state is tracked and restored on model change.
Previously, when the model data for categories and channels was changed, all unexpanded, or collapsed categories would automatically expand. This was due to the default state of the category `opened` property being restored (which was set to true) when the model data changed.
With this change in place, the opened state of each category is tracked in the parent component (`StatusChatListAndCategories`), and on each model change, the opened state is restored.
NOTE: it was tempting to the put the changes inside of the `StatusChatListCategory` component, however this would not work as the component is used as a delegate, and all state is wiped on each model change.
=> fix: track category opened state

src/StatusQ/Components/StatusChatList.qml
This broke because the emitted `mouse` coordinates where no longer correct
after we've moved the chat list item into a delegate model.
=> fix(StatusChatList): ensure right click popup opens in correct position

src/StatusQ/Popups/StatusSearchPopup.qml
This used `Theme.palette.black` before which doesn't work across differen themes.
`Theme.palette.directColor1` is the correct one to use here.
=> fix(StatusSearchPopup): use correct theme color for search result text

sandbox/StatusAccountSelectorPage.qml, sandbox/main.qml, src/StatusQ/Controls/StatusAccountSelector.qml, src/StatusQ/Controls/qmldir, src/StatusQ/Core/Theme/StatusDarkTheme.qml, src/StatusQ/Core/Theme/StatusLightTheme.qml, src/StatusQ/Core/Theme/ThemePalette.qml, src/StatusQ/Core/Utils/Utils.qml, statusq.qrc
This commit moves the original `AccountSelector` into StatusQ and makes it
a `StatusAccountSelector`. The API has been preserved. The only difference is
that it's internally relying completely on `StatusQ.Core.Theme` and `StatusQ.Controls`
components instead.
Usage:
```qml
import StatusQ.Controls 0.1
StatusAccountSelector {
accounts: ListModel {
ListElement {
name: "Pascal"
address: "0x1234567891011"
iconColor: "red"
balance: "0"
walletType: "generated"
assets: []
fiatBalance: "1199.02"
}
ListElement {
name: "Boris"
address: "0x123"
iconColor: "red"
balance: "0"
walletType: "generated"
assets: []
fiatBalance: "0"
}
ListElement {
name: "Alexandra"
address: "0x123"
iconColor: "yellow"
balance: "0"
walletType: "generated"
assets: []
fiatBalance: "0"
}
ListElement {
name: "Khushboo"
address: …
```
=> feat(StatusQ.Controls): introduce `StatusAccountSelector` component

sandbox/StatusAddressPage.qml, sandbox/main.qml, src/StatusQ/Components/StatusAddress.qml, src/StatusQ/Components/qmldir, statusq.qrc
This introduces a `StatusAddress` component which renders an address
and can be made `expandable` by applying a `width`:
```qml
// Simple case
StatusAddress {
text: "0x9ce0056c5fc6bb9459a4dcfa35eaad8c1fee5ce9"
}
// Expandable case
Item {
width: 200
height: childrenRect.height
StatusAddress {
text: "0x9ce0056c5fc6bb9459a4dcfa35eaad8c1fee5ce9"
expandable: true
width: parent.width
}
}
```
Closes #430
=> feat(StatusQ.Components): introduce `StatusAddress` component

src/StatusQ/Components/StatusListItem.qml
fix(StatusListItem): This solves the issue of channel list overlapping when a category is collapsed. 
The issue is not reproducible a 100% of time. In order to solve this bug, we have turned on the preventStealing flag for the mouseArea.
Checked for any side impacts but didn't find any.
Tried several times and this change seems to solve the bug. Feel free to reopen if you are still able to reproduce this behavior.
fixes #4047
=> fix(StatusListItem): This solves the issue of channel list overlapping when a category is collapsed.

sandbox/DemoApp.qml, sandbox/ListItems.qml, sandbox/Models.qml, src/StatusQ/Components/StatusChatList.qml, src/StatusQ/Components/StatusChatListAndCategories.qml, src/StatusQ/Components/StatusChatListCategory.qml, src/StatusQ/Components/StatusChatListItem.qml
Updated Models.qml for chats and communities models to reflect
changes due to refactor in the actual backend. Updated as well the relevant UI
components as properties like `model.chatId` is now `model.itemId` as well as in order to retrieve and display categories from the communities model.
`StatusChatList` and `StatusChatListAndCategories`
Relates to https://github.com/status-im/status-desktop/issues/4062
=> refactor(StatusChatList): updates due to chat & communities models refactored

src/StatusQ/Popups/StatusModal.qml, src/StatusQ/Popups/statusModal/StatusModalHeader.qml
This property can be used to hide the close button, as there are some
modals that shouldn't allow users to "x" modals away.
=> feat(StatusModal): introduce `hasCloseButton` property

src/StatusQ/Components/StatusChatListItem.qml
fix(StatusChatListItem): Fixes the issue of the chat list getting a highlight even when they are not really hovered
The issue is caused by the fact that the MouseArea returns containsMouse as true even when the item is not hovered.
The issue is reproduced when the model changes dynamically in the StatusChatList, thus causing the StatusChatListItem to be recreated and
this is when the containsMouse remains true even though the item is not hovered.
I see a bunch of issues in the QT bug list with regards to the containsMouse property but are still open.
A solution to this is to use HoverHandler which is a more reliable way getting hovered events for an item.
=> fix(StatusChatListItem): Fixes the issue of the chat list getting a highlight even when they are not really hovered

src/StatusQ/Components/StatusChatList.qml
`StatusChatList` component is able to display:
- chats for Chat section
- channels for Community section
- channels from a category from Community section
in cases 1. and 2. displayed items do not have `parentItemId` property and
it's not used in these cases.
This commit fixes that console error.
=> fix(StatusChatList): unexisting property name for chat item fixed

sandbox/controls/ListItems.qml, sandbox/demoapp/StatusAppCommunityView.qml, sandbox/demoapp/data/Models.qml, src/StatusQ/Components/StatusListItem.qml, src/StatusQ/Components/StatusMemberListItem.qml, src/StatusQ/Components/StatusSmartIdenticon.qml, src/StatusQ/Components/qmldir, statusq.qrc
Create new member component that includes online/offline indicator, trust indictor and optional chat key and original username.
To do that, a new component `StatusMemberListItem` has been created and included in `sandbox\controls\ListItems` for testing all its variants.
Extend existing components `StatusListItem` and `StatusSmartIndenticon`:
1. `StatusListItem` component has now the possibility of adding 2 icons after the title row.
2. `StatusSmartIndenticon` has now the possibility of displaying online/offline indicator (or a most generic state indicator).
Closes #515
Components/StatusMemberListItem [NEW]
Components/StatusListItem [MOD]
Components/StatusSmartIdenticon [MOD]
=> feat(StatusMemberListItem): Implement `StatusMemberListItem`

src/StatusQ/Components/StatusChatListAndCategories.qml, src/StatusQ/Components/StatusChatListCategory.qml
Fixes an issue where categories with no channels are being displayed as if they were normal channels:
While with this change, they look like this:
=> refactor: fix empty categories handling

sandbox/main.qml
Icon color in Icons page was broken as setting it
in main.qml was mistakenly removed. Set it back to
Theme.palette.primaryColor1
Closes #538
=> fix: Icon components had wrong color in sandbox app

src/StatusQ/Popups/StatusPopupMenu.qml
A MouseArea was set as an Overlay to the PopupMenu consuming all clicks outside the component until it was closed. Removed it as it's not necessary anymore.
Closes https://github.com/status-im/status-desktop/issues/3599
=> fix(StatusQ.Popups): removed overlay setting

sandbox/controls/ListItems.qml, sandbox/demoapp/ChatChannelView.qml, sandbox/demoapp/data/Models.qml, src/StatusQ/Components/StatusContactVerificationIcons.qml, src/StatusQ/Components/StatusListItem.qml, src/StatusQ/Components/StatusMemberListItem.qml, src/StatusQ/Components/StatusMessage.qml, src/StatusQ/Components/StatusMessageDetails.qml, src/StatusQ/Components/private/statusMessage/StatusMessageHeader.qml, src/StatusQ/Components/qmldir, statusq.qrc
Closes #542
It has been created a new component `StatusContactVerificationIcons`, that contains a row of specific contact verification icons, in order to avoid code duplicity in different project components. 
After the new component created, the following refactors have been done: 
- Refactor in `StatusMemberListItem`. It now uses `StatusContactVerificationIcons` component.
- Refactor in `StatusListItem`. It now contains a **Loader** for dynamically decide if a row icons component is defined aside the title.
- Refactor in `StatusMessageHeader` and `StatusMessage`. They now use `StatusContactVerificationIcons` component.
New `StatusContactVerificationIcons` component
Modify `StatusMemberListItem`, `StatusListItem`, `StatusMessageHeader` and `StatusMessage`
=> feat(StatusContactVerificationIcons): Create new row control that includes mutual connect and trust indicator icons

src/StatusQ/Components/StatusListItem.qml, src/StatusQ/Popups/StatusSearchLocationMenu.qml, src/StatusQ/Popups/StatusSearchPopup.qml
Makes it possible disable the propagation of the mouse event when it's not wanted, for example in the search popup, where if the user clicks the title, we want to show the profile popup, but not navigate to the channel
The original isn't changed  for other components using StatusListItem, since the property start at true
This was needed to fix the issue found by Abhi here: https://github.com/status-im/status-desktop/pull/4803#issuecomment-1043064425
=> fix(StatusListItem): add propagateTitleClicks property to StatusListItem

src/StatusQ/Components/StatusListItem.qml
When there is an icon, take it into account when calculating the left
padding
=> fix(@StatusListItem): fix left padding

.gitignore, sandbox/pages/StatusInputPage.qml, src/StatusQ/Components/StatusChatList.qml, src/StatusQ/Components/StatusListItem.qml, src/StatusQ/Controls/StatusInput.qml, src/StatusQ/Controls/Validators/StatusRegularExpressionValidator.qml, tests/TestControls/CMakeLists.txt, tests/TestControls/main.cpp, tests/TestControls/tst_test-statusinput.qml
Required for merging #5010
New entry
Allow typing only what matches regex
updates #4961
=> feat(StatusInput): Add ignore invalid input option to StatusInput

src/StatusQ/Core/StatusIconSettings.qml
This caused a breaking change where components that used to imply 1 charactersLen now showed no character at all because it defaulted to 0.
Fixes https://github.com/status-im/status-desktop/issues/5078
=> fix(StatusIconSettings): set charactersLen to 1 by default

.github/pull_request_template.md
We should ensure that every breaking change is tested in the status-desktop app. Each time there is a breaking change, there should be corresponding status-desktop PR that adapts to the changes and bumps the StatusQ version.
=> ci: add pull request template

src/StatusQ/Controls/StatusSeedPhraseInput.qml
The suggestion list should be showing up to 5 seed
word entries
=> fix(SeedPhraseInput): Fixing SeedPhraseInput control height

src/StatusQ/Controls/StatusBaseInput.qml, src/StatusQ/Popups/StatusSearchPopup.qml
Closes: https://github.com/status-im/status-desktop/issues/5059
=> fix(StatusQ.Popups): Replace TextEdit to StatusBaseInput for SearchPopup

sandbox/demoapp/CreateChatView.qml, sandbox/pages/StatusTagSelectorPage.qml, src/StatusQ/Components/StatusTagSelector.qml
Closes #531
Desktop updates: https://github.com/status-im/status-desktop/pull/5132
=> fix(StatusTagSelector): move suggestions popup inside component

src/StatusQ/Controls/StatusBaseInput.qml
=> fix(StatusBaseInput): fix default padding when leftComponent is loaded

sandbox/controls/ListItems.qml, src/StatusQ/Components/StatusExpandableItem.qml, src/StatusQ/Components/StatusListItem.qml, src/StatusQ/Controls/StatusBaseInput.qml, src/StatusQ/Controls/StatusInput.qml, src/StatusQ/Controls/StatusSeedPhraseInput.qml
Needed for task https://github.com/status-im/status-desktop/issues/4955
=> feat(StatusSeedPhraseInput): exposed keys on pressed signal

src/StatusQ/Controls/StatusBaseInput.qml
Placeholder text position updated for the `StatusBaseInput` component
that it follows the set text position.
This change is needed because of [this comment](https://github.com/status-im/status-desktop/pull/5245#issuecomment-1082310003).
=> fix(StatusBaseInput): placeholder position update

src/StatusQ/Controls/StatusSeedPhraseInput.qml
=> fix(StatusSeedPhraseInput): remove empty spaces in seed phrase input

src/StatusQ/Controls/StatusSeedPhraseInput.qml
Fixes issue on Windows where empty spaces are insterted in the input
field together with the word
=> fix(StatusSeedPhraseInput): added trim() also when seedWord selected from list

src/StatusQ/Components/StatusTagSelector.qml
Fix for https://github.com/status-im/status-desktop/issues/5199
=> fix(StatusTagSelector): fixing tag selector height

sandbox/pages/StatusListPickerPage.qml, src/StatusQ/Components/StatusListPicker.qml, src/StatusQ/Controls/StatusItemPicker.qml, src/StatusQ/Controls/StatusPickerButton.qml
Added signal `itemPickerChanged` to be directly notified when an item changes its selected property value.
Added new property `enableSelectableItem` to highlight an item when hovering.
Some documentation improvements.
=> fix(StatusListPicker): Added signal `itemPickerChanged` and property `enableSelectableItem`

src/StatusQ/Controls/StatusPickerButton.qml
Added property `textPixelSize` to be configurable in `StatusPickerButton`.
=> fix(StatusPickerButton): Added property `textPixelSize` to be configurable

src/StatusQ/Components/StatusTagSelector.qml
needed for: https://github.com/status-im/status-desktop/issues/5294
=> fix(StatusTagSelector): adding wrap mode in text edit

src/StatusQ/Controls/StatusInput.qml
=> feat(StatusInput): Adding component documentation

sandbox/pages/StatusListPickerPage.qml, src/StatusQ/Components/StatusListPicker.qml
- Disabled uncheck option if component is configured as single selection mode.
- Added binding to reset searcher input text when picker is closed.
BREAKING CHANGE: Renamed `searchText` property for `placeholderSearchText` to control placeholder text in searcher and added / used existing `searchText` property to control  searcher input text.
**IMPORTANT:** Breaking changes will be resolved in the following [PR](https://github.com/status-im/status-desktop/pull/5417) in desktop.
- nice to have: add it to the …
=> fix(StatusListPicker): Disabled uncheck option and reset searcher

sandbox/demoapp/StatusAppChatView.qml, src/StatusQ/Components/StatusChatList.qml
Needed for https://github.com/status-im/status-desktop/issues/5627
=> fix(StatusChatList): Added property to control item's highlight

sandbox/pages/StatusToastMessagePage.qml, src/StatusQ/Components/StatusToastMessage.qml
What is changed:
- `open` property set to `true` by default
- `duration` property added (if set to anything greater than 0, will trigger
close toast signal after `duration` milliseconds)
- `close` signal is now emitted once animation gets completed
=> feat(StatusQ.Components): `StatusToastMessage` updated

src/StatusQ/Controls/StatusBaseInput.qml
Found this issue when I activated the `forceActiveFocus` in the CreateCommunityPopup. It would trigger the red border.
The problem was that the textChanged event would trigger, even though nothing was changed. 
I added this condition to make sure dirty doesn't get flagged.
=> fix(StatusBaseInput): fix dirty being set when the text didn't change

src/StatusQ/Controls/StatusBaseInput.qml, src/StatusQ/Controls/StatusSeedPhraseInput.qml
This is needed for https://github.com/status-im/status-desktop/issues/5409
It improves the SeedInput:
- support up and down arrows to go up and down the suggestion list
- Support tab and enter for auto-complete
- go to next only when word is complete
The StatusBaseInput also has a new prop so that we can pass the return pressed event.
=> Improve Seed Input

sandbox/pages/StatusListPickerPage.qml, src/StatusQ/Components/StatusListPicker.qml
fix(StatusListPicker): Add an option to allign the menu with respective the buttons and keep right alligned as the default one
fixes #5633
=> fix(StatusListPicker): Add an option to allign the menu with respective the buttons and keep right alligned as the default one

src/StatusQ/Controls/StatusBaseButton.qml
When button changed from loading to their normal shape it kept the width of the loader as it was visible in the row component.
It has been added a binding between loader `visible` property and root `loading` property that fixes the issue with the width.
Also, removed some `break` leftovers.
Fixes #5606 --> https://github.com/status-im/status-desktop/issues/5606
=> fix(StatusBaseButton): After loading, button keeps loader width, so the button size is bigger

sandbox/demoapp/CreateChatView.qml, src/StatusQ/Components/StatusTagSelector.qml
Needed for: https://github.com/status-im/status-desktop/issues/5640
=> fix(StatusTagSelector): Added up/down hard keys navigation

sandbox/controls/ListItems.qml, src/StatusQ/Components/StatusListItem.qml
Tiny fix to keep text always inside boundaries
=> fix(StatusListItem): Fix title text out of the expected boundaries

src/StatusQ/Controls/StatusBaseButton.qml
…h/size when it enters loading state
fixes #656
=> fix(StatusBaseButton): Button component should keep its original size when it enters loading state

src/StatusQ/Controls/StatusBaseInput.qml, src/StatusQ/Core/Utils/Emoji.qml
Makes it match the design 
Part of https://github.com/status-im/status-desktop/issues/5673
=> fix(StatusBaseInput): adjust emoji size and position in base input

src/StatusQ/Components/StatusImageCropPanel.qml, src/StatusQ/Controls/StatusImageCrop.qml
Currently, only fit-image is supported as a minimum limit
This change adds the option to fill the crop window with image content as the minimum allowed zoom, which is required by the `status-go` crop function.
=> improvement(StatusImageCrop): add option to limit zooming to fill mode

src/StatusQ/Components/StatusTagSelector.qml
Fixes https://github.com/status-im/status-desktop/issues/5712
=> fix(StatusTagSelector): hide contact when it is selected

src/StatusQ/Controls/StatusSeedPhraseInput.qml
Needed for: https://github.com/status-im/status-desktop/issues/5669
=> fix(StatusSeedPhraseInput): anchored component to its parent bottom

src/StatusQ/Controls/StatusProgressBar.qml
For https://github.com/status-im/status-desktop/issues/5702
=> fix(StatusProgressBar): Hide text in bar if it does not fit

src/StatusQ/Components/StatusNavigationListItem.qml
The click handler used inside the component broke in one of the latest
changes done in `StatusListItem` where it expects two arguments being
passed to its click handler.
This commit fixes it by supplying all needed arguments (where `itemId`
is always `''` unless set differently)
=> fix(StatusNavigationListItem): make click handler work again

src/StatusQ/Components/StatusImageCropPanel.qml, src/StatusQ/Controls/StatusImageCrop.qml
The initial fit was computed for the square crop-window
updates: 5118
=> fix(StatusImageCrop): fix wrong initial image fit

sandbox/demoapp/CreateChatView.qml, src/StatusQ/Components/StatusTagSelector.qml
Needed for: https://github.com/status-im/status-desktop/issues/5875
=> feat(StatusTagSelector): Added colorIdForPubkeyGetter property

src/StatusQ/Popups/StatusSearchLocationMenu.qml, src/StatusQ/Popups/StatusSearchPopup.qml, src/StatusQ/Popups/StatusSearchPopupMenuItem.qml
needed by: https://github.com/status-im/status-desktop/pull/5940
=> fix(StatusSearchPopup): add color hash to chat icons

sandbox/controls/Layout.qml, sandbox/demoapp/data/Models.qml, sandbox/pages/StatusTagSelectorPage.qml, src/StatusQ/Components/StatusTagSelector.qml, src/StatusQ/Controls/StatusTagItem.qml, src/StatusQ/Controls/qmldir, statusq.qrc
Closes #694
- Different tag color depending if the entry `isReadonly` or not.
- Tag disabled if the entry `isReadonly`.
- Possibility to show icon if entry contains the proper info.
- Added property `orderByReadonly` to position `isReadonly` entries in the left.
Updated sandbox project examples according to new tag updates.
Layouts / StatusTagsSelector
StatusTagsSelectorPage
demoApp/CreateChat
https://user-images.githubusercontent.com/97019400/171397952-d971fdb3-a855-40f5-a3bf-5b405620987b.mov
- nice to have: …
=> feat(StatusTagSelector): Introduced readonly tags and possibility of icon

src/StatusQ/Components/StatusMemberListItem.qml, src/StatusQ/Components/StatusTagSelector.qml
=> chore: adapt to new user/member backend models structure

sandbox/controls/Buttons.qml, sandbox/controls/Popups.qml, src/StatusQ/Controls/StatusBaseButton.qml, src/StatusQ/Controls/StatusFloatingButtonsSelector.qml, src/StatusQ/Controls/qmldir, src/StatusQ/Popups/StatusModal.qml
feat(StatusModalFloatingButtonsSelector): Implementing the floating accounts selector widget.
Needed under wallet design https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=3311%3A177552
https://user-images.githubusercontent.com/60327365/169160811-804bee04-2b26-45ed-b082-422d3a3819c9.mov
=> feat(StatusModalFloatingButtonsSelector): Implementing the floating buttons selector widget

sandbox/demoapp/data/Models.qml, sandbox/main.qml, sandbox/pages/StatusCommunityTagsPage.qml, src/StatusQ/Components/StatusCommunityTags.qml, src/StatusQ/Components/StatusEmoji.qml, src/StatusQ/Components/qmldir, src/StatusQ/Controls/StatusCommunityTag.qml, src/StatusQ/Controls/qmldir
For https://github.com/status-im/status-desktop/issues/5680
=> feat(StatusCommunityTags): Add community tags component

src/StatusQ/Controls/StatusFlatRoundButton.qml
Small fix. The warning appeared when switching channels. The parent must have not been initiated or something. Using the ID solves the issue.
=> chore(StatusFlatRoundButon): fix warning related to hovered property

sandbox/controls/Buttons.qml, src/StatusQ/Controls/StatusRoundButton.qml
- Transparent background but when hovered, like Primary type in idle state.
- Updated sandbox with the new type.
https://user-images.githubusercontent.com/97019400/175244789-58e0c37a-cb2b-4088-887f-a24fabf292dc.mov
=> feat(StatusRoundButton): Added `Tertiary` type

src/StatusQ/Components/StatusChatToolBar.qml, src/StatusQ/Controls/StatusActivityCenterButton.qml
Activity center button has now the same size than the other toolbar buttons.
Fixes https://github.com/status-im/status-desktop/issues/6216
https://user-images.githubusercontent.com/97019400/175265391-383f9bfa-23af-4524-91f6-75e323c554f9.mov
=> fix(StatusChatToolBar): Updated activity center button size

src/StatusQ/Popups/StatusStackModal.qml
For https://github.com/status-im/status-desktop/pull/6270
=> feat(StatusStackModal): add subheader and remove explicit width

sandbox/sandbox.pro
since most of the compilation time is spent on creating the QRC bundle
and the resulting binary is quite huge, advice the `rcc` compiler to add
support for "big resources"
(cf https://doc.qt.io/qt-6/resources.html#embedding-large-files)
Also pass the env $LDFLAGS to qmake (to be able to link e.g. with mold,
which again greatly reduces the time to link the binary)
this leads to 6-10x faster time when recompiling
(Linux, gcc 12.1.1, mold 1.3.0)
BEFORE:
Clean build:
real	0m57,256s
user	1m25,869s
sys	0m40,963s
Incremental build, one file touched:
real	0m54,323s
user	0m54,012s
sys	0m2,934s
AFTER:
Clean build:
real	0m7,276s
user	0m21,001s
sys	0m37,256s
Incremental build, one file touched:
real	0m5,569s
user	0m4,850s
sys	0m0,840s
- the scope should be the component's name e.g: …
=> fix(@sandbox): greatly speed up (re)build times

sandbox/main.cpp
Similar to what we did in status desktop under [@status-im/status-desktop/#6335](https://github.com/status-im/status-desktop/pull/6335)
- since Qt 5.xy, hover is not enabled by default for QQC2, so enable it
unconditionally as we are a desktop app anyway
- this fixes several hover effects being broken, mostly for builtin
components like MenuItem and some buttons (eg. the leftmost NavBar)
where we haven't enabled those with `hoverEnabled: true` explicitely
=> fix(sandbox): enable the hover effects by default

sandbox/demoapp/data/Models.qml, src/StatusQ/Core/StatusIcon.qml
- set the Image's `sourceSize` only if it's an SVG, otherwise it is
rendered blurry
- remove antialiasing/mipmap; it's not the correct fix, doesn't really
improve the visual quality for smallish items like icons and just causes
memory/GPU overhead
=> fix(StatusIcon): flag/currency icons are rendered blurred

src/StatusQ/Components/StatusExpandableItem.qml, src/StatusQ/Controls/StatusPinInput.qml, src/StatusQ/Controls/StatusSwitch.qml
I have noticed that there are lot of: `QML NumberAnimation: setRunning() cannot be used on non-root animation nodes` WRNgs in logs - as also @caybro [noticed](https://github.com/status-im/StatusQ/pull/744#issuecomment-1171037383). Looks like they are pointing to animations with `running:` property set when higher level nodes (animations or states) are handling `running`.
This PR is to fix the warnings and let QT decide when animation should be running:
a) in transitions: when states are changing
b) in nested animations: higher level animation should handle "children" animations
_This is my very first PR in this repos, so Hi!_ 👋 😄 
- when adding new components, the scope is the module e.g: `feat(StatusQ.Controls): …
=> fix: handle animations by higher level nodes or states

src/StatusQ/Popups/StatusStackModal.qml
call `updateRightButtons()` also on creation to correctly initialize the
Next and Finish buttons in derived classes, when one overrrides these
can be seen in the Backup Seed dialog where the Next button is not
enabled even though all 3 boxes are checked
=> fix(StatusStackModal): init the next/finish buttons

src/StatusQ/Popups/StatusStackModal.qml
This adds a possible `prevAction` hook to `stackLayout.currentItem`
which is triggered (if it exists) when the stack modal's back button is
hit.
=> feat(StatusStackModal): introduce `prevAction` API

src/StatusQ/Controls/StatusCheckBox.qml
add a possibility to override the font size for the contentItem's StatusBaseText
otherwise it's impossible to do stuff like:
```qml
StatusCheckBox {
font.pixelSize: 15
}
```
=> hotfix(StatusCheckBox): enable setting the font size

src/StatusQ/Core/StatusIconBackgroundSettings.qml, src/StatusQ/Popups/StatusMenuItemDelegate.qml, src/StatusQ/Popups/StatusSearchLocationMenu.qml, src/StatusQ/Popups/StatusSearchPopup.qml
Needed for status-im/status-desktop#6428
- set the default icon background color to "transparent"; otherwise it
would be black when unset
- set the popup default size to 560x122 (as designed)
- add placeholder for the search field
- correct the font and icon sizes, spacing and margins according to
design
- fix some warnings
=> fix(SearchPopup): align with design

src/StatusQ/Components/StatusChatListAndCategories.qml
Required by Issue status-im/status-desktop#6542
Exposes `highlightItem` from `StatusChatListAndCategories` for consistency with raw `StatusChatList` component.
=> feat(StatusChatListAndCategories) expose highlightItem prop from StatusChatListAndCategories

src/StatusQ/Controls/StatusBanner.qml
let the text elide on the right side if the parent width is smaller
than ours
(also fix some docu typos)
Related: status-im/status-desktop#6600
Screenshot with the fix:
=> fix(StatusBanner): TestNet banner overlaps left panel

sandbox/qml.qrc, src/StatusQ/Layout/StatusAppNavBar.qml, src/statusq.qrc
it should be 24px from the bottom according to the design
plus a hotfix to unbreak the build (StatusAssetSelector has been removed from sources but not from QRC)
=> fix(StatusAppNavBar): fix profile icon bottom margin

src/StatusQ/Core/StatusListView.qml
Tiny fix to make StatusListView and StatusScrollView more similar for usage. availableWidth/availableHeight can be used instead of anchors in StatusListView's delegate to get maximum size that doesn't cause scrolling
=> feat(StatusListView): Add availableWidth/availableHeight to api

src/StatusQ/Popups/StatusSearchPopup.qml
New `resetSearchLocationClicked` signal introduced.
Click on `X` button is emitting `resetSearchLocationClicked` signal and
lets a component which is using this one to decide what to do instead just
reseting search selection locally to this component.
Needed for https://github.com/status-im/status-desktop/issues/6551
=> fix(StatusSearchPopup): reset search location

src/StatusQ/Core/StatusScrollView.qml
As part of https://github.com/status-im/status-desktop/issues/6609, I found that the backgropund property is no longer usable. I'm removing the use of `background` in status-desktop, which was only the CommunityColumnView.
=> chore(StatusScrollView): remove unused background property

src/StatusQ/Controls/StatusFloatingButtonsSelector.qml, src/StatusQ/Core/Theme/StatusColors.qml, src/StatusQ/Core/Theme/StatusDarkTheme.qml, src/StatusQ/Core/Theme/StatusLightTheme.qml, src/StatusQ/Core/Theme/ThemePalette.qml, src/StatusQ/Popups/StatusModal.qml
fix(StatusModal): Adapt the status modal to have a user defined background color
Add a new color for StatusFloatingButtonSelector
- [x  test changes in both light and dark theme?
=> fix(StatusModal): Adapt the status modal to have a user defined background color

src/StatusQ/Controls/StatusInput.qml
As part of https://github.com/status-im/status-desktop/issues/6022
=> fix(StatusInput): Replaced layout spacing with margins

src/StatusQ/Components/StatusChatList.qml, src/StatusQ/Components/StatusTagSelector.qml, src/StatusQ/Controls/StatusChatInfoButton.qml
Added `objectName` properties needed for automation
=> Test/issue 6444 - Added `objectName` properties needed for automation

src/StatusQ/Controls/StatusInput.qml
Adds the optional `force` argument to the `validate` function of StatusInput to force the validation, even if the validationMode does not permit it (eg: the validation mode is "only when dirty" and the field was never dirty)
I used this in the small refactor I did to switch the Input used in the Join public chat modal to a StatusInput.
=> feat(StatusInput): add force argument to validate to force validation

sandbox/main.qml, sandbox/pages/StatusTextAreaPage.qml, src/StatusQ/Controls/StatusTextArea.qml, src/StatusQ/Controls/qmldir, src/StatusQ/Layout/StatusAppTwoPanelLayout.qml, src/statusq.qrc
Implements a standard QQC2 TextArea control with Status styling
Closes #236
Light theme:
Dark theme:
=> feat(StatusTextArea): Implement StatusTextArea

src/StatusQ/Controls/StatusSeedPhraseInput.qml
Closes: status-im/status-desktop#6720
Screenshots:
=> fix(StatusSeedPhraseInput): Back up seed phrase inputs are missing spacing

src/StatusQ/Components/StatusListPicker.qml, src/StatusQ/Components/StatusListPickerProxies.qml, src/statusq.qrc
needed by https://github.com/status-im/status-desktop/issues/6662, see: https://github.com/status-im/status-desktop/blob/c30a9b014919fc0ea0dc56742fd0d7dc26c16ce6/ui/app/AppLayouts/Profile/views/LanguageView.qml#L146-L154
=> chore(StatusListPicker): enable picker to work with incompatible models

src/StatusQ/Controls/StatusInput.qml
=> fix(StatusInput): setting default 44px in min/max height

src/StatusQ/Components/StatusChatList.qml, src/StatusQ/Components/StatusChatListAndCategories.qml, src/StatusQ/Components/StatusChatListCategory.qml
This change is a necessary first step for further refactor of the functionality regarding community's chats list reordering and fixing bugs in this area.
Fixes: status-im/status-desktop#6709
=> chore(StatusChatList): Use SortFilterProxyModel instead of filtering functions

src/StatusQ/Controls/StatusBaseInput.qml
Needed for https://github.com/status-im/status-desktop/issues/6730
=> fix(StatusBaseInput): added left margin between text and left component

src/StatusQ/Components/StatusChatList.qml, src/StatusQ/Components/StatusChatListAndCategories.qml, src/StatusQ/Core/Utils/Utils.qml
After reordering chats or chat categories the order of elements in the list should reflect order in the underlying model. Reorders done via DelegateModel when dragging reordered item should be revoked to avoid improper sorting.
required by: status-im/status-desktop#6597, status-im/status-desktop#6722
affected:
StatusChatList, StatusChatListAndCategories
=> chore(StatusChatList): Keep sync with underlying model after reordering

src/StatusQ/Components/StatusImageCropPanel.qml, src/StatusQ/Controls/StatusSlider.qml
- change StatusSlider y to be vertically centered
Fixes [#](https://github.com/status-im/status-desktop/issues/6725
Required by https://github.com/status-im/status-desktop/pull/6811
StatusSlider after changes
StatusImageCropPanel after changes
Status-desktop fixed
=> fix(StatusImageCropPanel) vertically align slider in ImageCropPanel

sandbox/pages/StatusAddressPage.qml, src/StatusQ/Components/StatusAddress.qml, src/StatusQ/Components/StatusAddressPanel.qml, src/StatusQ/Components/qmldir, src/statusq.qrc
Some images and video is not up to date, tweaked and fixed in the meantime
Light theme
Dark theme
StatusQ vs. Design
Hovered
Wallet settings
https://user-images.githubusercontent.com/47554641/182799214-505900a3-5f43-48f4-b28e-822f4e084015.mov
=> feature(StatusAddressPanel): Implement generic address display control

src/StatusQ/Components/StatusChatList.qml
=> fix(StatusChatList): fix wrong id used

src/StatusQ/Controls/StatusColorRadioButton.qml, src/StatusQ/Controls/StatusColorSelectorGrid.qml
Expose diameters properties to adjust StatusColorRadioButtons to design: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2457%3A345186
Required by Issue #5982
=> feat(StatusColorRadioButton): expose radio button diameter property

src/StatusQ/Controls/StatusBaseInput.qml, src/StatusQ/Popups/StatusStackModal.qml
No need to calculate margins manually
=> fix(StatusStackView): Use availableWidth for content

src/StatusQ/Controls/StatusInput.qml
P.S i've fixed error message display in the component but there is still problem with Utils.getErrorMessage
- [x ] test changes in [status-desktop](https://github.com/status-im/status-desktop)
=> fix(StatusInput): Add labelPadding customisation and improve height calculation

sandbox/controls/Others.qml, src/StatusQ/Components/StatusDatePicker.qml, src/StatusQ/Components/qmldir, src/StatusQ/Controls/StatusComboBox.qml, src/statusq.qrc
nothing fancy, just a combo box with a calendar popup; needed for the
discord import tool UI
Related to status-im/status-desktop#6081
Screenshots:
=> feat(StatusDatePicker): introduce StatusDatePicker component

sandbox/pages/StatusInputPage.qml, src/StatusQ/Controls/StatusSeedPhraseInput.qml
Signal `doneInsertingWord` wasn't emitted when words was updated by adding one letter resulting in another valid word, e.g. `win` -> `wine`.
This PR withdraws part of the change introduced in https://github.com/status-im/StatusQ/pull/648. It should be tested carefully for regressions.
required by: https://github.com/status-im/status-desktop/issues/6619
=> fix(StatusSeedPhraseInput): fix notification of inserting word done

sandbox/pages/StatusImageCropPanelPage.qml, src/StatusQ/Components/StatusImageCropPanel.qml, src/StatusQ/Controls/StatusImageCrop.qml, tests/CMakeLists.txt
Fix by disabling layering, leftover from the previous approach of not using Canvas.
Also, implemented a proper approach for TODOs regarding artefacts workaround
Adds more testing cases to the sandbox app, used to reproduce and investigate the issue
| Previous | Fixed |
| :-- | :-- |
| ![image](https://user-images.githubusercontent.com/47554641/183070338-a49b5d3a-a408-4be3-a4e1-6b9183f071b1.png) | ![image](https://user-images.githubusercontent.com/47554641/183076720-898ab3bf-1c97-4b2e-a890-28c044cff150.png) |
Note: found a corner case in `StatusImageCropPanel` when the anchor didn't snap to the bottom of the parent and added `anchors.bottomMargin: -1` to all items to account for this issue/side-effect.
=> fix(StatusImageCrop): fix artefacts due to offscreen caching

src/StatusQ/Controls/StatusTabButton.qml
Needed by https://github.com/status-im/status-desktop/issues/6786
Required by https://github.com/status-im/status-desktop/pull/6914
=> fix(StatusTabButton) adjust tab button height

src/StatusQ/Components/StatusCommunityTags.qml
For https://github.com/status-im/status-desktop/pull/6917
https://user-images.githubusercontent.com/2522130/183500433-73dcd69e-d6ea-4272-8841-06eeebdc35af.mov
=> fix(StatusCommunityTags): fix width calculation

src/StatusQ/Controls/StatusColorSelectorGrid.qml
fix(StatusColorSelectorGrid): Expose the Color Repeater for Squish testing
=> fix(StatusColorSelectorGrid): Expose the Color Repeater for Squish testing

src/StatusQ/Popups/StatusMenuItemDelegate.qml
Needed for https://github.com/status-im/status-desktop/issues/6830
Required by https://github.com/status-im/status-desktop/pull/6991
Design vs Sandbox app
Design vs Desktop app
=> fix(StatusMenuItemDelegate): adjust menu item height

src/StatusQ/Popups/StatusPopupMenu.qml
Needed for https://github.com/status-im/status-desktop/issues/6822
Required by https://github.com/status-im/status-desktop/pull/7011
Sandbox menu
https://user-images.githubusercontent.com/6445843/184596852-46ff5550-d08e-49fb-88cb-8a9ecc831973.mp4
Desktop app menu
https://user-images.githubusercontent.com/6445843/184597625-0507c476-4a2b-4bc1-91b5-16dd1b914a0b.mp4
Latest version with StatusListView …
=> fix(StatusPopupMenu): update popup content to support big margins

src/StatusQ/Components/StatusChatListAndCategories.qml
=> fix(StatusChatListAndCategories): duplicate objectName

src/StatusQ/Controls/StatusBaseInput.qml, src/StatusQ/Controls/StatusInput.qml
add dirty alias
Fixes https://github.com/status-im/status-desktop/issues/6825
Needed by https://github.com/status-im/status-desktop/pull/7048
BREAKING CHANGE: StatusInput now emits signal for errors change
Sandbox app
https://user-images.githubusercontent.com/6445843/184929450-25fdeaf9-093d-4b72-b493-198eaa08319e.mp4
Desktop app
https://user-images.githubusercontent.com/6445843/185091201-33872dc1-7115-49f7-a2c8-4eedc5b65ae5.mp4
=> fix(StatusInput)!: trigger errors bindings

sandbox/controls/ListItems.qml, sandbox/demoapp/StatusAppChatView.qml, src/StatusQ/Components/StatusChatList.qml, src/StatusQ/Components/StatusChatListAndCategories.qml, src/StatusQ/Components/StatusChatListCategory.qml, src/StatusQ/Components/StatusChatListCategoryItem.qml, src/StatusQ/Components/StatusChatListItem.qml, src/StatusQ/Components/StatusListItem.qml
The culprit here is at the very bottom, in StatusListItem: the toplevel
item was a MouseArea handling the clicks and this causes problems as any
extra buttons placed on top of it get their mouseClick events delivered
in wrong order (after StatusListItem). Fix this by having a MouseArea
handling click events behind the actual toplevel item as a last resort,
catch all handler  plus the actual "sensor" being just a MouseArea that
handles merely the hover events
- drop unneeded onPressed/onReleased handlers in StatusChatListCategoryItem
- fix some warnings (typos, unreachable code, shadowed variables)
Fixes: status-im/status-desktop#6733
- when adding new components, the scope is the module e.g: …
=> fix(StatusChatListCategory): Clicking on a category should toggle it

src/StatusQ/Controls/StatusTabButton.qml
Needed for https://github.com/status-im/status-desktop/issues/6787
StatusTabButton gains proper mouse cursor (hand) when active
=> fix(StatusTabButton): display hand cursor on hover when enabled

src/StatusQ/Components/StatusMessage.qml, src/StatusQ/Components/StatusMessageDetails.qml, src/StatusQ/Components/private/statusMessage/StatusMessageHeader.qml
This is a property that allows for adding information about the origin
of a message (e.g. "Imported from discord").
This will most likely be only useful for messages that have been
imported from any other platform.
Because importing from other platforms requires those message to be
signed by a Status Account, it's undesirable to render the public key of
the account that signed imported messages.
Hence, when there's a `messageOriginInfo`, we don't render the elided
public key.
- nice to have: add it to the …
=> feat(StatusMessage): add `messageOriginInfo` property

src/StatusQ/Layout/StatusAppNavBar.qml
This PR changes bounds behavior in StatusAppNavBar:
- outer list: not draggable
- communities list: not draggable when sufficient space,
drag and overshot otherwise
Needed for https://github.com/status-im/status-desktop/issues/6805
https://user-images.githubusercontent.com/20650004/186013466-27cabb1f-ebcd-4adb-940f-078692e22829.mp4
=> chore(StatusAppNavBar): List views' bounds behavior refined

src/StatusQ/Components/StatusImageCropPanel.qml
Sets the cursor shape to `Qt.SizeAllCursor` in `StatusImageCropPanel`.
Note: on Ubuntu there is a bug causing that Qt.SizeAllCursor is displayed as Qt.ClosedHandCursor cursor (tested on Qt 5.14, 5.15 and 6.3). It should be checked on Windows and Mac. If the problem exists only on linux I would suggest merging and reporting bug to Qt.
https://user-images.githubusercontent.com/20650004/185951283-36412a6a-c9fb-438d-8405-a56bef4718d8.mp4
=> fix(StatusImageCropPanel): display SizeAllCursor cursor when over image

src/StatusQ/Components/StatusMessage.qml, src/StatusQ/Components/private/statusMessage/StatusMessageHeader.qml
This property allows for enabling/disabling whether or not the profile
picture and display name of a message is clickable and also dictates the
cursor type accordingly.
The reason this is being introduced is that, with imported messages from
other systems (e.g. discord, telegram etc), we don't want the user to
trigger the popup menu for more profile information because we don't
know any profile information of messages coming from such systems.
Such messages are signed by the community.
Closes https://github.com/status-im/status-desktop/issues/6680
- in case of new features, …
=> feat(StatusMessage): introduce `profileClickable` property

sandbox/controls/Controls.qml, sandbox/qml.qrc, src/StatusQ/Controls/StatusRadioButton.qml
- fix the control's width (don't have to be explicit, the QQC2 Control
takes care of calculating the implicitWidth/Height automatically based on
contents)
- fix propagating the font to the contentItem's text
- while at it, fix the metrics to be able to support RTL
languages too (it was broken for Arabic for example, and we are getting translations for these languages)
- some smaller cleanups too
Screenshot:
=> fix(StatusRadioButton): StatusRadioButton can't be fully clicked

src/StatusQ/Components/StatusTagSelector.qml
=> fix(StatusTagSelector): forbid removing readonly tags

src/StatusQ/Controls/StatusSelect.qml
Fix space due to hardcoded width
Not used anywhere else in desktop app
=> fix(StatusSelect): fix implicitWidth to account for content size

src/StatusQ/Components/StatusMessage.qml, src/StatusQ/Components/private/statusMessage/StatusMessageReply.qml
This is analogue to `profileClickable` available on `StatusMessage`,
preventing users to activate a reply-to-message's profile avatar.
At the time of this commit, this is only the case for imported messages.
So we can derive that, if `StatusMessage.profileClickable` is false, then
`StatusMessageReply.profileClickable` is also false.
Hence, we don't need to expose this property to higher level APIs.
=> feat(StatusMessageReply): introduce `profileClickable` property

src/StatusQ/Controls/StatusBaseButton.qml
`StatusBaseButton` comes with a `MouseArea` that is disabled when the button is set to being disabled. Prior to this commit it's *also* disabled when the button is in `loading` state.
This makes sense because a button that is in `loading` state shouldn't not emit any click signals or trigger hover indications.
There's a scenario though in which we want render a tooltip on top of the button which is in `loading` state. For the tooltip to show, the `MouseArea` of the button needs to be enabled.
Hence, this commit adjust `StatusBaseButton`'s behaviour to *not* disable the `MouseArea` when it's `loading`. Mouse events are already prevented via the `loading` flag. So the only thing left to do is to ensure the button doesn't trigger any hover indication when in `loading` state.
- the scope …
=> fix(StatusBaseButton): keep `MouseArea` enabled when in `loading` state

sandbox/controls/ListItems.qml, src/StatusQ/Components/StatusListItem.qml
Needed for https://github.com/status-im/status-desktop/issues/6972
Required by https://github.com/status-im/status-desktop/pull/7263
Update main area right margin to take in consideration big number of title icons
=> fix(StatusListItem): adjust placement of title icons

sandbox/main.qml, sandbox/pages/StatusItemSelectorPage.qml, src/StatusQ/Components/StatusItemSelector.qml, src/StatusQ/Components/StatusListItem.qml, src/StatusQ/Components/StatusListItemTag.qml
StatusItemSelector:
- no internal popup handling (better flexibility in terms of positioning)
- "add" button exposed
- onItemClicked signal added
Additionally:
- minor positioning fixes in StatusListItem and StatusListItemTag
- StatusItemSelectorPage updated and added to main.qml
needed for https://github.com/status-im/status-desktop/issues/6339, https://github.com/status-im/status-desktop/pull/7261
=> feat(StatusItemSelector): improved reusablity, addItem and popup handling removed

src/StatusQ/Components/StatusDateGroupLabel.qml
- fix evaluating "Today" and "Yesterday"; can't just compare the two Date objects, the timestamp will always differ so need to compare year/month/day only
- best attempt to have the month translated, and year added if they differ (until Qt6 at least, left a TODO)
Closes #843
A translated date + "Yesterday" shown:
Today/yesterday fixed:
=> fix: StatusDateGroupLabel doesn't support i18n and has no year

src/StatusQ/Components/StatusMessage.qml
Prior to this commit, a `StatusMessage` can hold only a single `messageImage`.
There will be scenarios where messages can have multiple attachments. This is the case when importing messages from discord. Hence, this commit introduces a new `messageAttachments` property which is a whitespace separated list of attachment URLs (very analogous to the already existing `linkUrls` property).
For now, we can safely assume these URLs will resolve to image content. In future versions however, we might want to support additional content types to handle any byte stream.
We will then change `messageAttachments` from `string` to a list model that holds `attachment`s where we also have access to its `contentType`. This will allow us to decide at runtime which component should be used to view/play the …
=> feat(StatusMessage): add support for `messageAttachments`

src/StatusQ/Components/StatusExpandableItem.qml
fix(StatusExpandableItem): Added new padding for Tertitary type expandable item, a flag to set separator to visible true or false
=> fix(StatusExpandableItem): Added new padding for Tertitary type expandable item, a flag to set separator to visible true or false

sandbox/controls/Buttons.qml, src/StatusQ/Controls/StatusBaseButton.qml
turns out we can indeed have only one MouseArea to handle both the cursor and intercepting the event in the "loading" state
=> hotfix: unbreak "pointing hand" cursor

sandbox/controls/Controls.qml, sandbox/controls/Layout.qml, src/StatusQ/Controls/StatusChatInfoButton.qml
- fix the "pinned messages" counter; resort to showing just the number in case of constrained space
- add plural handling (Fixes #899)
- modernize using layouts (Fixes #898)
- add some more examples
=> fix(StatusChatInfoButton): pinned messages counter

src/StatusQ/Components/StatusItemSelector.qml
Gives possibility to use icons in StatusItemSelector.
Required by: https://github.com/status-im/status-desktop/issues/6040
=> chore(StatusItemSelector): allow of using icons

src/StatusQ/Controls/StatusBaseButton.qml, src/StatusQ/Core/Theme/ThemePalette.qml
Font family set for StatusBaseButton, font variants moved to internal object to avoid accessing them directly.
In the future we should consider switching to variable fonts in order to avoid loading multiple font variants.
=> fix(StatusBaseButton): font family and weight fixed

src/StatusQ/Controls/StatusChatInfoButton.qml
do not display the subtitle when it's empty
=> fix(StatusChatInfoButton): fix vertical title alignment

src/StatusQ/Components/StatusMessage.qml
This functionality is needed to hide image links when image is unfurled.
Needed for: https://github.com/status-im/status-desktop/pull/7452
=> feat(StatusMessage): add 'hideMessage' property to allow hiding main message text

src/StatusQ/Components/StatusListItem.qml
=> fix(StatusListItem): Adding padding in the inline tags
